using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace WindowsFomKontrolleri
{
    public partial class SehirIlceDataBound : Form
    {
        public SehirIlceDataBound()
        {
            InitializeComponent();
        }

        private void SehirIlceDataBound_Load(object sender, EventArgs e)
        {
            cb_sehir.DataSource = SehirDoldur();
            cb_sehir.DisplayMember = "Isim";
            cb_sehir.ValueMember = "ID";
        }

        public List<Sehir> SehirDoldur()
        {
            List<Sehir> sehirler = new List<Sehir>();
            sehirler.Add(new Sehir() { ID = 1, Isim = "Adana" });
            sehirler.Add(new Sehir { ID = 2, Isim = "Adıyaman" });
            sehirler.Add(new Sehir { ID = 3, Isim = "Afyonkarahisar" });
            sehirler.Add(new Sehir { ID = 4, Isim = "Ağrı" });
            sehirler.Add(new Sehir { ID = 5, Isim = "Amasya" });
            sehirler.Add(new Sehir { ID = 6, Isim = "Ankara" });
            sehirler.Add(new Sehir { ID = 7, Isim = "Antalya" });
            sehirler.Add(new Sehir { ID = 8, Isim = "Artvin" });
            sehirler.Add(new Sehir { ID = 9, Isim = "Aydın" });
            sehirler.Add(new Sehir { ID = 10, Isim = "Balıkesir" });
            sehirler.Add(new Sehir { ID = 11, Isim = "Bilecik" });
            sehirler.Add(new Sehir { ID = 12, Isim = "Bingöl" });
            sehirler.Add(new Sehir { ID = 13, Isim = "Bitlis" });
            sehirler.Add(new Sehir { ID = 14, Isim = "Bolu" });
            sehirler.Add(new Sehir { ID = 15, Isim = "Burdur" });
            sehirler.Add(new Sehir { ID = 16, Isim = "Bursa" });
            sehirler.Add(new Sehir { ID = 17, Isim = "Çanakkale" });
            sehirler.Add(new Sehir { ID = 18, Isim = "Çankırı" });
            sehirler.Add(new Sehir { ID = 19, Isim = "Çorum" });
            sehirler.Add(new Sehir { ID = 20, Isim = "Denizli" });
            sehirler.Add(new Sehir { ID = 21, Isim = "Diyarbakır" });
            sehirler.Add(new Sehir { ID = 22, Isim = "Edirne" });
            sehirler.Add(new Sehir { ID = 23, Isim = "Elazığ" });
            sehirler.Add(new Sehir { ID = 24, Isim = "Erzincan" });
            sehirler.Add(new Sehir { ID = 25, Isim = "Erzurum" });
            sehirler.Add(new Sehir { ID = 26, Isim = "Eskişehir" });
            sehirler.Add(new Sehir { ID = 27, Isim = "Gaziantep" });
            sehirler.Add(new Sehir { ID = 28, Isim = "Giresun" });
            sehirler.Add(new Sehir { ID = 29, Isim = "Gümüşhane" });
            sehirler.Add(new Sehir { ID = 30, Isim = "Hakkari" });
            sehirler.Add(new Sehir { ID = 31, Isim = "Hatay" });
            sehirler.Add(new Sehir { ID = 32, Isim = "Isparta" });
            sehirler.Add(new Sehir { ID = 33, Isim = "Mersin" });
            sehirler.Add(new Sehir { ID = 34, Isim = "İstanbul" });
            sehirler.Add(new Sehir { ID = 35, Isim = "İzmir" });
            sehirler.Add(new Sehir { ID = 36, Isim = "Kars" });
            sehirler.Add(new Sehir { ID = 37, Isim = "Kastamonu" });
            sehirler.Add(new Sehir { ID = 38, Isim = "Kayseri" });
            sehirler.Add(new Sehir { ID = 39, Isim = "Kırklareli" });
            sehirler.Add(new Sehir { ID = 40, Isim = "Kırşehir" });
            sehirler.Add(new Sehir { ID = 41, Isim = "Kocaeli" });
            sehirler.Add(new Sehir { ID = 42, Isim = "Konya" });
            sehirler.Add(new Sehir { ID = 43, Isim = "Kütahya" });
            sehirler.Add(new Sehir { ID = 44, Isim = "Malatya" });
            sehirler.Add(new Sehir { ID = 45, Isim = "Manisa" });
            sehirler.Add(new Sehir { ID = 46, Isim = "Kahramanmaraş" });
            sehirler.Add(new Sehir { ID = 47, Isim = "Mardin" });
            sehirler.Add(new Sehir { ID = 48, Isim = "Muğla" });
            sehirler.Add(new Sehir { ID = 49, Isim = "Muş" });
            sehirler.Add(new Sehir { ID = 50, Isim = "Nevşehir" });
            sehirler.Add(new Sehir { ID = 51, Isim = "Niğde" });
            sehirler.Add(new Sehir { ID = 52, Isim = "Ordu" });
            sehirler.Add(new Sehir { ID = 53, Isim = "Rize" });
            sehirler.Add(new Sehir { ID = 54, Isim = "Sakarya" });
            sehirler.Add(new Sehir { ID = 55, Isim = "Samsun" });
            sehirler.Add(new Sehir { ID = 56, Isim = "Siirt" });
            sehirler.Add(new Sehir { ID = 57, Isim = "Sinop" });
            sehirler.Add(new Sehir { ID = 58, Isim = "Sivas" });
            sehirler.Add(new Sehir { ID = 59, Isim = "Tekirdağ" });
            sehirler.Add(new Sehir { ID = 60, Isim = "Tokat" });
            sehirler.Add(new Sehir { ID = 61, Isim = "Trabzon" });
            sehirler.Add(new Sehir { ID = 62, Isim = "Tunceli" });
            sehirler.Add(new Sehir { ID = 63, Isim = "Şanlıurfa" });
            sehirler.Add(new Sehir { ID = 64, Isim = "Uşak" });
            sehirler.Add(new Sehir { ID = 65, Isim = "Van" });
            sehirler.Add(new Sehir { ID = 66, Isim = "Yozgat" });
            sehirler.Add(new Sehir { ID = 67, Isim = "Zonguldak" });
            sehirler.Add(new Sehir { ID = 68, Isim = "Aksaray" });
            sehirler.Add(new Sehir { ID = 69, Isim = "Bayburt" });
            sehirler.Add(new Sehir { ID = 70, Isim = "Karaman" });
            sehirler.Add(new Sehir { ID = 71, Isim = "Kırıkkale" });
            sehirler.Add(new Sehir { ID = 72, Isim = "Batman" });
            sehirler.Add(new Sehir { ID = 73, Isim = "Şırnak" });
            sehirler.Add(new Sehir { ID = 74, Isim = "Bartın" });
            sehirler.Add(new Sehir { ID = 75, Isim = "Ardahan" });
            sehirler.Add(new Sehir { ID = 76, Isim = "Iğdır" });
            sehirler.Add(new Sehir { ID = 77, Isim = "Yalova" });
            sehirler.Add(new Sehir { ID = 78, Isim = "Karabük" });
            sehirler.Add(new Sehir { ID = 79, Isim = "Kilis" });
            sehirler.Add(new Sehir { ID = 80, Isim = "Osmaniye" });
            sehirler.Add(new Sehir { ID = 81, Isim = "Düzce" });
            return sehirler;
        }

        public List<Ilce> IlceDoldur()
        {
            List<Ilce> ilceler = new List<Ilce>();

            ilceler.Add(new Ilce() { ID = 99133, Isim = "Şakirpaşa Havalimanı", SehirID = 1 });
            ilceler.Add(new Ilce() { ID = 2033, Isim = "ÇUKUROVA", SehirID = 1 });
            ilceler.Add(new Ilce() { ID = 2032, Isim = "SARIÇAM", SehirID = 1 });
            ilceler.Add(new Ilce() { ID = 1806, Isim = "İMAMOĞLU", SehirID = 1 });
            ilceler.Add(new Ilce() { ID = 1757, Isim = "ALADAĞ", SehirID = 1 });
            ilceler.Add(new Ilce() { ID = 1748, Isim = "YÜREĞİR", SehirID = 1 });
            ilceler.Add(new Ilce() { ID = 1734, Isim = "YUMURTALIK", SehirID = 1 });
            ilceler.Add(new Ilce() { ID = 1687, Isim = "TUFANBEYLİ", SehirID = 1 });
            ilceler.Add(new Ilce() { ID = 1588, Isim = "SAİMBEYLİ", SehirID = 1 });
            ilceler.Add(new Ilce() { ID = 1580, Isim = "POZANTI", SehirID = 1 });
            ilceler.Add(new Ilce() { ID = 1486, Isim = "KOZAN", SehirID = 1 });
            ilceler.Add(new Ilce() { ID = 1443, Isim = "KARATAŞ", SehirID = 1 });
            ilceler.Add(new Ilce() { ID = 1437, Isim = "KARAİSALI", SehirID = 1 });
            ilceler.Add(new Ilce() { ID = 1329, Isim = "FEKE", SehirID = 1 });
            ilceler.Add(new Ilce() { ID = 1219, Isim = "CEYHAN", SehirID = 1 });
            ilceler.Add(new Ilce() { ID = 1104, Isim = "SEYHAN", SehirID = 1 });
            ilceler.Add(new Ilce() { ID = 99139, Isim = "Adıyaman Havalimanı", SehirID = 2 });
            ilceler.Add(new Ilce() { ID = 1989, Isim = "TUT", SehirID = 2 });
            ilceler.Add(new Ilce() { ID = 1985, Isim = "SİNCİK", SehirID = 2 });
            ilceler.Add(new Ilce() { ID = 1592, Isim = "SAMSAT", SehirID = 2 });
            ilceler.Add(new Ilce() { ID = 1425, Isim = "KAHTA", SehirID = 2 });
            ilceler.Add(new Ilce() { ID = 1354, Isim = "GÖLBAŞI", SehirID = 2 });
            ilceler.Add(new Ilce() { ID = 1347, Isim = "GERGER", SehirID = 2 });
            ilceler.Add(new Ilce() { ID = 1246, Isim = "ÇELİKHAN", SehirID = 2 });
            ilceler.Add(new Ilce() { ID = 1182, Isim = "BESNİ", SehirID = 2 });
            ilceler.Add(new Ilce() { ID = 1105, Isim = "MERKEZ", SehirID = 2 });
            ilceler.Add(new Ilce() { ID = 99132, Isim = "Afyon Havalimanı", SehirID = 3 });
            ilceler.Add(new Ilce() { ID = 1961, Isim = "KIZILÖREN", SehirID = 3 });
            ilceler.Add(new Ilce() { ID = 1944, Isim = "HOCALAR", SehirID = 3 });
            ilceler.Add(new Ilce() { ID = 1923, Isim = "EVCİLER", SehirID = 3 });
            ilceler.Add(new Ilce() { ID = 1906, Isim = "ÇOBANLAR", SehirID = 3 });
            ilceler.Add(new Ilce() { ID = 1809, Isim = "İSCEHİSAR", SehirID = 3 });
            ilceler.Add(new Ilce() { ID = 1773, Isim = "BAYAT", SehirID = 3 });
            ilceler.Add(new Ilce() { ID = 1771, Isim = "BAŞMAKÇI", SehirID = 3 });
            ilceler.Add(new Ilce() { ID = 1664, Isim = "ŞUHUT", SehirID = 3 });
            ilceler.Add(new Ilce() { ID = 1639, Isim = "SULTANDAĞI", SehirID = 3 });
            ilceler.Add(new Ilce() { ID = 1626, Isim = "SİNANPAŞA", SehirID = 3 });
            ilceler.Add(new Ilce() { ID = 1594, Isim = "SANDIKLI", SehirID = 3 });
            ilceler.Add(new Ilce() { ID = 1404, Isim = "İHSANİYE", SehirID = 3 });
            ilceler.Add(new Ilce() { ID = 1306, Isim = "EMİRDAĞ", SehirID = 3 });
            ilceler.Add(new Ilce() { ID = 1281, Isim = "DİNAR", SehirID = 3 });
            ilceler.Add(new Ilce() { ID = 1267, Isim = "DAZKIRI", SehirID = 3 });
            ilceler.Add(new Ilce() { ID = 1239, Isim = "ÇAY", SehirID = 3 });
            ilceler.Add(new Ilce() { ID = 1200, Isim = "BOLVADİN", SehirID = 3 });
            ilceler.Add(new Ilce() { ID = 1108, Isim = "MERKEZ", SehirID = 3 });
            ilceler.Add(new Ilce() { ID = 99140, Isim = "Ağrı Ahmed-i Hani Havalimanı", SehirID = 4 });
            ilceler.Add(new Ilce() { ID = 1691, Isim = "TUTAK", SehirID = 4 });
            ilceler.Add(new Ilce() { ID = 1667, Isim = "TAŞLIÇAY", SehirID = 4 });
            ilceler.Add(new Ilce() { ID = 1568, Isim = "PATNOS", SehirID = 4 });
            ilceler.Add(new Ilce() { ID = 1379, Isim = "HAMUR", SehirID = 4 });
            ilceler.Add(new Ilce() { ID = 1301, Isim = "ELEŞKİRT", SehirID = 4 });
            ilceler.Add(new Ilce() { ID = 1287, Isim = "DOĞUBAYAZIT", SehirID = 4 });
            ilceler.Add(new Ilce() { ID = 1283, Isim = "DİYADİN", SehirID = 4 });
            ilceler.Add(new Ilce() { ID = 1111, Isim = "MERKEZ", SehirID = 4 });
            ilceler.Add(new Ilce() { ID = 99166, Isim = "Amasya Merzifon Havalimanı", SehirID = 5 });
            ilceler.Add(new Ilce() { ID = 1938, Isim = "HAMAMÖZÜ", SehirID = 5 });
            ilceler.Add(new Ilce() { ID = 1668, Isim = "TAŞOVA", SehirID = 5 });
            ilceler.Add(new Ilce() { ID = 1641, Isim = "SULUOVA", SehirID = 5 });
            ilceler.Add(new Ilce() { ID = 1524, Isim = "MERZİFON", SehirID = 5 });
            ilceler.Add(new Ilce() { ID = 1368, Isim = "GÜMÜŞHACIKÖY", SehirID = 5 });
            ilceler.Add(new Ilce() { ID = 1363, Isim = "GÖYNÜCEK", SehirID = 5 });
            ilceler.Add(new Ilce() { ID = 1134, Isim = "MERKEZ", SehirID = 5 });
            ilceler.Add(new Ilce() { ID = 99134, Isim = "Ankara Esenboğa Havalimanı", SehirID = 6 });
            ilceler.Add(new Ilce() { ID = 2034, Isim = "PURSAKLAR", SehirID = 6 });
            ilceler.Add(new Ilce() { ID = 1924, Isim = "EVREN", SehirID = 6 });
            ilceler.Add(new Ilce() { ID = 1922, Isim = "ETİMESGUT", SehirID = 6 });
            ilceler.Add(new Ilce() { ID = 1872, Isim = "AKYURT", SehirID = 6 });
            ilceler.Add(new Ilce() { ID = 1815, Isim = "KAHRAMANKAZAN", SehirID = 6 });
            ilceler.Add(new Ilce() { ID = 1747, Isim = "SİNCAN", SehirID = 6 });
            ilceler.Add(new Ilce() { ID = 1746, Isim = "MAMAK", SehirID = 6 });
            ilceler.Add(new Ilce() { ID = 1745, Isim = "KEÇİÖREN", SehirID = 6 });
            ilceler.Add(new Ilce() { ID = 1744, Isim = "GÖLBAŞI", SehirID = 6 });
            ilceler.Add(new Ilce() { ID = 1723, Isim = "YENİMAHALLE", SehirID = 6 });
            ilceler.Add(new Ilce() { ID = 1658, Isim = "ŞEREFLİKOÇHİSAR", SehirID = 6 });
            ilceler.Add(new Ilce() { ID = 1578, Isim = "POLATLI", SehirID = 6 });
            ilceler.Add(new Ilce() { ID = 1539, Isim = "NALLIHAN", SehirID = 6 });
            ilceler.Add(new Ilce() { ID = 1473, Isim = "KIZILCAHAMAM", SehirID = 6 });
            ilceler.Add(new Ilce() { ID = 1427, Isim = "KALECİK", SehirID = 6 });
            ilceler.Add(new Ilce() { ID = 1387, Isim = "HAYMANA", SehirID = 6 });
            ilceler.Add(new Ilce() { ID = 1365, Isim = "GÜDÜL", SehirID = 6 });
            ilceler.Add(new Ilce() { ID = 1302, Isim = "ELMADAĞ", SehirID = 6 });
            ilceler.Add(new Ilce() { ID = 1260, Isim = "ÇUBUK", SehirID = 6 });
            ilceler.Add(new Ilce() { ID = 1231, Isim = "ÇANKAYA", SehirID = 6 });
            ilceler.Add(new Ilce() { ID = 1227, Isim = "ÇAMLIDERE", SehirID = 6 });
            ilceler.Add(new Ilce() { ID = 1187, Isim = "BEYPAZARI", SehirID = 6 });
            ilceler.Add(new Ilce() { ID = 1167, Isim = "BALA", SehirID = 6 });
            ilceler.Add(new Ilce() { ID = 1157, Isim = "AYAŞ", SehirID = 6 });
            ilceler.Add(new Ilce() { ID = 1130, Isim = "ALTINDAĞ", SehirID = 6 });
            ilceler.Add(new Ilce() { ID = 99141, Isim = "Gazipaşa Havalimanı", SehirID = 7 });
            ilceler.Add(new Ilce() { ID = 99135, Isim = "Antalya Havalimanı", SehirID = 7 });
            ilceler.Add(new Ilce() { ID = 2039, Isim = "MURATPAŞA", SehirID = 7 });
            ilceler.Add(new Ilce() { ID = 2038, Isim = "KONYAALTI", SehirID = 7 });
            ilceler.Add(new Ilce() { ID = 2037, Isim = "KEPEZ", SehirID = 7 });
            ilceler.Add(new Ilce() { ID = 2036, Isim = "DÖŞEMEALTI", SehirID = 7 });
            ilceler.Add(new Ilce() { ID = 2035, Isim = "AKSU", SehirID = 7 });
            ilceler.Add(new Ilce() { ID = 1959, Isim = "KEMER", SehirID = 7 });
            ilceler.Add(new Ilce() { ID = 1946, Isim = "İBRADI", SehirID = 7 });
            ilceler.Add(new Ilce() { ID = 1811, Isim = "DEMRE", SehirID = 7 });
            ilceler.Add(new Ilce() { ID = 1616, Isim = "SERİK", SehirID = 7 });
            ilceler.Add(new Ilce() { ID = 1512, Isim = "MANAVGAT", SehirID = 7 });
            ilceler.Add(new Ilce() { ID = 1492, Isim = "KUMLUCA", SehirID = 7 });
            ilceler.Add(new Ilce() { ID = 1483, Isim = "KORKUTELİ", SehirID = 7 });
            ilceler.Add(new Ilce() { ID = 1451, Isim = "KAŞ", SehirID = 7 });
            ilceler.Add(new Ilce() { ID = 1370, Isim = "GÜNDOĞMUŞ", SehirID = 7 });
            ilceler.Add(new Ilce() { ID = 1337, Isim = "GAZİPAŞA", SehirID = 7 });
            ilceler.Add(new Ilce() { ID = 1333, Isim = "FİNİKE", SehirID = 7 });
            ilceler.Add(new Ilce() { ID = 1303, Isim = "ELMALI", SehirID = 7 });
            ilceler.Add(new Ilce() { ID = 1138, Isim = "MERKEZ", SehirID = 7 });
            ilceler.Add(new Ilce() { ID = 1126, Isim = "ALANYA", SehirID = 7 });
            ilceler.Add(new Ilce() { ID = 1121, Isim = "AKSEKİ", SehirID = 7 });
            ilceler.Add(new Ilce() { ID = 2105, Isim = "KEMALPAŞA", SehirID = 8 });
            ilceler.Add(new Ilce() { ID = 1828, Isim = "MURGUL", SehirID = 8 });
            ilceler.Add(new Ilce() { ID = 1736, Isim = "YUSUFELİ", SehirID = 8 });
            ilceler.Add(new Ilce() { ID = 1653, Isim = "ŞAVŞAT", SehirID = 8 });
            ilceler.Add(new Ilce() { ID = 1395, Isim = "HOPA", SehirID = 8 });
            ilceler.Add(new Ilce() { ID = 1202, Isim = "BORÇKA", SehirID = 8 });
            ilceler.Add(new Ilce() { ID = 1152, Isim = "MERKEZ", SehirID = 8 });
            ilceler.Add(new Ilce() { ID = 1147, Isim = "ARHAVİ", SehirID = 8 });
            ilceler.Add(new Ilce() { ID = 1145, Isim = "ARDANUÇ", SehirID = 8 });
            ilceler.Add(new Ilce() { ID = 2076, Isim = "EFELER", SehirID = 9 });
            ilceler.Add(new Ilce() { ID = 2000, Isim = "DİDİM", SehirID = 9 });
            ilceler.Add(new Ilce() { ID = 1968, Isim = "KÖŞK", SehirID = 9 });
            ilceler.Add(new Ilce() { ID = 1957, Isim = "KARPUZLU", SehirID = 9 });
            ilceler.Add(new Ilce() { ID = 1807, Isim = "İNCİRLİOVA", SehirID = 9 });
            ilceler.Add(new Ilce() { ID = 1781, Isim = "BUHARKENT", SehirID = 9 });
            ilceler.Add(new Ilce() { ID = 1724, Isim = "YENİPAZAR", SehirID = 9 });
            ilceler.Add(new Ilce() { ID = 1640, Isim = "SULTANHİSAR", SehirID = 9 });
            ilceler.Add(new Ilce() { ID = 1637, Isim = "SÖKE", SehirID = 9 });
            ilceler.Add(new Ilce() { ID = 1542, Isim = "NAZİLLİ", SehirID = 9 });
            ilceler.Add(new Ilce() { ID = 1498, Isim = "KUYUCAK", SehirID = 9 });
            ilceler.Add(new Ilce() { ID = 1497, Isim = "KUŞADASI", SehirID = 9 });
            ilceler.Add(new Ilce() { ID = 1479, Isim = "KOÇARLI", SehirID = 9 });
            ilceler.Add(new Ilce() { ID = 1435, Isim = "KARACASU", SehirID = 9 });
            ilceler.Add(new Ilce() { ID = 1348, Isim = "GERMENCİK", SehirID = 9 });
            ilceler.Add(new Ilce() { ID = 1256, Isim = "ÇİNE", SehirID = 9 });
            ilceler.Add(new Ilce() { ID = 1206, Isim = "BOZDOĞAN", SehirID = 9 });
            ilceler.Add(new Ilce() { ID = 1159, Isim = "MERKEZ", SehirID = 9 });
            ilceler.Add(new Ilce() { ID = 99142, Isim = "Balıkesir Merkez Havalimanı", SehirID = 10 });
            ilceler.Add(new Ilce() { ID = 99107, Isim = "Balıkesir Koca Seyit Havalimanı", SehirID = 10 });
            ilceler.Add(new Ilce() { ID = 2078, Isim = "KARESİ", SehirID = 10 });
            ilceler.Add(new Ilce() { ID = 2077, Isim = "ALTIEYLÜL", SehirID = 10 });
            ilceler.Add(new Ilce() { ID = 1928, Isim = "GÖMEÇ", SehirID = 10 });
            ilceler.Add(new Ilce() { ID = 1824, Isim = "MARMARA", SehirID = 10 });
            ilceler.Add(new Ilce() { ID = 1644, Isim = "SUSURLUK", SehirID = 10 });
            ilceler.Add(new Ilce() { ID = 1619, Isim = "SINDIRGI", SehirID = 10 });
            ilceler.Add(new Ilce() { ID = 1608, Isim = "SAVAŞTEPE", SehirID = 10 });
            ilceler.Add(new Ilce() { ID = 1514, Isim = "MANYAS", SehirID = 10 });
            ilceler.Add(new Ilce() { ID = 1462, Isim = "KEPSUT", SehirID = 10 });
            ilceler.Add(new Ilce() { ID = 1418, Isim = "İVRİNDİ", SehirID = 10 });
            ilceler.Add(new Ilce() { ID = 1384, Isim = "HAVRAN", SehirID = 10 });
            ilceler.Add(new Ilce() { ID = 1360, Isim = "GÖNEN", SehirID = 10 });
            ilceler.Add(new Ilce() { ID = 1310, Isim = "ERDEK", SehirID = 10 });
            ilceler.Add(new Ilce() { ID = 1294, Isim = "EDREMİT", SehirID = 10 });
            ilceler.Add(new Ilce() { ID = 1291, Isim = "DURSUNBEY", SehirID = 10 });
            ilceler.Add(new Ilce() { ID = 1216, Isim = "BURHANİYE", SehirID = 10 });
            ilceler.Add(new Ilce() { ID = 1191, Isim = "BİGADİÇ", SehirID = 10 });
            ilceler.Add(new Ilce() { ID = 1171, Isim = "BANDIRMA", SehirID = 10 });
            ilceler.Add(new Ilce() { ID = 1169, Isim = "BALYA", SehirID = 10 });
            ilceler.Add(new Ilce() { ID = 1168, Isim = "MERKEZ", SehirID = 10 });
            ilceler.Add(new Ilce() { ID = 1161, Isim = "AYVALIK", SehirID = 10 });
            ilceler.Add(new Ilce() { ID = 1948, Isim = "İNHİSAR", SehirID = 11 });
            ilceler.Add(new Ilce() { ID = 1857, Isim = "YENİPAZAR", SehirID = 11 });
            ilceler.Add(new Ilce() { ID = 1636, Isim = "SÖĞÜT", SehirID = 11 });
            ilceler.Add(new Ilce() { ID = 1571, Isim = "PAZARYERİ", SehirID = 11 });
            ilceler.Add(new Ilce() { ID = 1559, Isim = "OSMANELİ", SehirID = 11 });
            ilceler.Add(new Ilce() { ID = 1359, Isim = "GÖLPAZARI", SehirID = 11 });
            ilceler.Add(new Ilce() { ID = 1210, Isim = "BOZÜYÜK", SehirID = 11 });
            ilceler.Add(new Ilce() { ID = 1192, Isim = "MERKEZ", SehirID = 11 });
            ilceler.Add(new Ilce() { ID = 99167, Isim = "Bingöl Havalimanı", SehirID = 12 });
            ilceler.Add(new Ilce() { ID = 1996, Isim = "YEDİSU", SehirID = 12 });
            ilceler.Add(new Ilce() { ID = 1855, Isim = "YAYLADERE", SehirID = 12 });
            ilceler.Add(new Ilce() { ID = 1750, Isim = "ADAKLI", SehirID = 12 });
            ilceler.Add(new Ilce() { ID = 1633, Isim = "SOLHAN", SehirID = 12 });
            ilceler.Add(new Ilce() { ID = 1475, Isim = "KİĞI", SehirID = 12 });
            ilceler.Add(new Ilce() { ID = 1446, Isim = "KARLIOVA", SehirID = 12 });
            ilceler.Add(new Ilce() { ID = 1344, Isim = "GENÇ", SehirID = 12 });
            ilceler.Add(new Ilce() { ID = 1193, Isim = "MERKEZ", SehirID = 12 });
            ilceler.Add(new Ilce() { ID = 1798, Isim = "GÜROYMAK", SehirID = 13 });
            ilceler.Add(new Ilce() { ID = 1669, Isim = "TATVAN", SehirID = 13 });
            ilceler.Add(new Ilce() { ID = 1537, Isim = "MUTKİ", SehirID = 13 });
            ilceler.Add(new Ilce() { ID = 1394, Isim = "HİZAN", SehirID = 13 });
            ilceler.Add(new Ilce() { ID = 1196, Isim = "MERKEZ", SehirID = 13 });
            ilceler.Add(new Ilce() { ID = 1112, Isim = "AHLAT", SehirID = 13 });
            ilceler.Add(new Ilce() { ID = 1106, Isim = "ADİLCEVAZ", SehirID = 13 });
            ilceler.Add(new Ilce() { ID = 1997, Isim = "YENİÇAĞA", SehirID = 14 });
            ilceler.Add(new Ilce() { ID = 1916, Isim = "DÖRTDİVAN", SehirID = 14 });
            ilceler.Add(new Ilce() { ID = 1610, Isim = "SEBEN", SehirID = 14 });
            ilceler.Add(new Ilce() { ID = 1531, Isim = "MUDURNU", SehirID = 14 });
            ilceler.Add(new Ilce() { ID = 1522, Isim = "MENGEN", SehirID = 14 });
            ilceler.Add(new Ilce() { ID = 1466, Isim = "KIBRISCIK", SehirID = 14 });
            ilceler.Add(new Ilce() { ID = 1364, Isim = "GÖYNÜK", SehirID = 14 });
            ilceler.Add(new Ilce() { ID = 1346, Isim = "GEREDE", SehirID = 14 });
            ilceler.Add(new Ilce() { ID = 1199, Isim = "MERKEZ", SehirID = 14 });
            ilceler.Add(new Ilce() { ID = 1903, Isim = "ÇELTİKÇİ", SehirID = 15 });
            ilceler.Add(new Ilce() { ID = 1899, Isim = "ÇAVDIR", SehirID = 15 });
            ilceler.Add(new Ilce() { ID = 1874, Isim = "ALTINYAYLA", SehirID = 15 });
            ilceler.Add(new Ilce() { ID = 1816, Isim = "KEMER", SehirID = 15 });
            ilceler.Add(new Ilce() { ID = 1813, Isim = "KARAMANLI", SehirID = 15 });
            ilceler.Add(new Ilce() { ID = 1728, Isim = "YEŞİLOVA", SehirID = 15 });
            ilceler.Add(new Ilce() { ID = 1672, Isim = "TEFENNİ", SehirID = 15 });
            ilceler.Add(new Ilce() { ID = 1357, Isim = "GÖLHİSAR", SehirID = 15 });
            ilceler.Add(new Ilce() { ID = 1215, Isim = "MERKEZ", SehirID = 15 });
            ilceler.Add(new Ilce() { ID = 1211, Isim = "BUCAK", SehirID = 15 });
            ilceler.Add(new Ilce() { ID = 1109, Isim = "AĞLASUN", SehirID = 15 });
            ilceler.Add(new Ilce() { ID = 99124, Isim = "Bursa Yenişehir Havalimanı", SehirID = 16 });
            ilceler.Add(new Ilce() { ID = 1960, Isim = "KESTEL", SehirID = 16 });
            ilceler.Add(new Ilce() { ID = 1935, Isim = "GÜRSU", SehirID = 16 });
            ilceler.Add(new Ilce() { ID = 1859, Isim = "YILDIRIM", SehirID = 16 });
            ilceler.Add(new Ilce() { ID = 1832, Isim = "OSMANGAZİ", SehirID = 16 });
            ilceler.Add(new Ilce() { ID = 1829, Isim = "NİLÜFER", SehirID = 16 });
            ilceler.Add(new Ilce() { ID = 1799, Isim = "HARMANCIK", SehirID = 16 });
            ilceler.Add(new Ilce() { ID = 1783, Isim = "BÜYÜKORHAN", SehirID = 16 });
            ilceler.Add(new Ilce() { ID = 1725, Isim = "YENİŞEHİR", SehirID = 16 });
            ilceler.Add(new Ilce() { ID = 1554, Isim = "ORHANGAZİ", SehirID = 16 });
            ilceler.Add(new Ilce() { ID = 1553, Isim = "ORHANELİ", SehirID = 16 });
            ilceler.Add(new Ilce() { ID = 1535, Isim = "MUSTAFAKEMALPAŞA", SehirID = 16 });
            ilceler.Add(new Ilce() { ID = 1530, Isim = "MUDANYA", SehirID = 16 });
            ilceler.Add(new Ilce() { ID = 1457, Isim = "KELES", SehirID = 16 });
            ilceler.Add(new Ilce() { ID = 1434, Isim = "KARACABEY", SehirID = 16 });
            ilceler.Add(new Ilce() { ID = 1420, Isim = "İZNİK", SehirID = 16 });
            ilceler.Add(new Ilce() { ID = 1411, Isim = "İNEGÖL", SehirID = 16 });
            ilceler.Add(new Ilce() { ID = 1343, Isim = "GEMLİK", SehirID = 16 });
            ilceler.Add(new Ilce() { ID = 99168, Isim = "Çanakkale Havalimanı", SehirID = 17 });
            ilceler.Add(new Ilce() { ID = 99128, Isim = "Gökçeada Havalimanı", SehirID = 17 });
            ilceler.Add(new Ilce() { ID = 1722, Isim = "YENİCE", SehirID = 17 });
            ilceler.Add(new Ilce() { ID = 1503, Isim = "LAPSEKİ", SehirID = 17 });
            ilceler.Add(new Ilce() { ID = 1408, Isim = "GÖKÇEADA", SehirID = 17 });
            ilceler.Add(new Ilce() { ID = 1340, Isim = "GELİBOLU", SehirID = 17 });
            ilceler.Add(new Ilce() { ID = 1326, Isim = "EZİNE", SehirID = 17 });
            ilceler.Add(new Ilce() { ID = 1293, Isim = "ECEABAT", SehirID = 17 });
            ilceler.Add(new Ilce() { ID = 1230, Isim = "MERKEZ", SehirID = 17 });
            ilceler.Add(new Ilce() { ID = 1229, Isim = "ÇAN", SehirID = 17 });
            ilceler.Add(new Ilce() { ID = 1205, Isim = "BOZCAADA", SehirID = 17 });
            ilceler.Add(new Ilce() { ID = 1190, Isim = "BİGA", SehirID = 17 });
            ilceler.Add(new Ilce() { ID = 1180, Isim = "BAYRAMİÇ", SehirID = 17 });
            ilceler.Add(new Ilce() { ID = 1160, Isim = "AYVACIK", SehirID = 17 });
            ilceler.Add(new Ilce() { ID = 1963, Isim = "KORGUN", SehirID = 18 });
            ilceler.Add(new Ilce() { ID = 1885, Isim = "BAYRAMÖREN", SehirID = 18 });
            ilceler.Add(new Ilce() { ID = 1817, Isim = "KIZILIRMAK", SehirID = 18 });
            ilceler.Add(new Ilce() { ID = 1765, Isim = "ATKARACALAR", SehirID = 18 });
            ilceler.Add(new Ilce() { ID = 1718, Isim = "YAPRAKLI", SehirID = 18 });
            ilceler.Add(new Ilce() { ID = 1649, Isim = "ŞABANÖZÜ", SehirID = 18 });
            ilceler.Add(new Ilce() { ID = 1555, Isim = "ORTA", SehirID = 18 });
            ilceler.Add(new Ilce() { ID = 1494, Isim = "KURŞUNLU", SehirID = 18 });
            ilceler.Add(new Ilce() { ID = 1399, Isim = "ILGAZ", SehirID = 18 });
            ilceler.Add(new Ilce() { ID = 1300, Isim = "ELDİVAN", SehirID = 18 });
            ilceler.Add(new Ilce() { ID = 1248, Isim = "ÇERKEŞ", SehirID = 18 });
            ilceler.Add(new Ilce() { ID = 1232, Isim = "MERKEZ", SehirID = 18 });
            ilceler.Add(new Ilce() { ID = 1976, Isim = "OĞUZLAR", SehirID = 19 });
            ilceler.Add(new Ilce() { ID = 1972, Isim = "LAÇİN", SehirID = 19 });
            ilceler.Add(new Ilce() { ID = 1911, Isim = "DODURGA", SehirID = 19 });
            ilceler.Add(new Ilce() { ID = 1850, Isim = "UĞURLUDAĞ", SehirID = 19 });
            ilceler.Add(new Ilce() { ID = 1778, Isim = "BOĞAZKALE", SehirID = 19 });
            ilceler.Add(new Ilce() { ID = 1642, Isim = "SUNGURLU", SehirID = 19 });
            ilceler.Add(new Ilce() { ID = 1558, Isim = "OSMANCIK", SehirID = 19 });
            ilceler.Add(new Ilce() { ID = 1556, Isim = "ORTAKÖY", SehirID = 19 });
            ilceler.Add(new Ilce() { ID = 1520, Isim = "MECİTÖZÜ", SehirID = 19 });
            ilceler.Add(new Ilce() { ID = 1445, Isim = "KARGI", SehirID = 19 });
            ilceler.Add(new Ilce() { ID = 1414, Isim = "İSKİLİP", SehirID = 19 });
            ilceler.Add(new Ilce() { ID = 1259, Isim = "MERKEZ", SehirID = 19 });
            ilceler.Add(new Ilce() { ID = 1177, Isim = "BAYAT", SehirID = 19 });
            ilceler.Add(new Ilce() { ID = 1124, Isim = "ALACA", SehirID = 19 });
            ilceler.Add(new Ilce() { ID = 99143, Isim = "Denizli Çardak Havalimanı", SehirID = 20 });
            ilceler.Add(new Ilce() { ID = 2079, Isim = "MERKEZEFENDİ", SehirID = 20 });
            ilceler.Add(new Ilce() { ID = 1889, Isim = "BOZKURT", SehirID = 20 });
            ilceler.Add(new Ilce() { ID = 1888, Isim = "BEYAĞAÇ", SehirID = 20 });
            ilceler.Add(new Ilce() { ID = 1881, Isim = "BAKLAN", SehirID = 20 });
            ilceler.Add(new Ilce() { ID = 1871, Isim = "PAMUKKALE", SehirID = 20 });
            ilceler.Add(new Ilce() { ID = 1840, Isim = "SERİNHİSAR", SehirID = 20 });
            ilceler.Add(new Ilce() { ID = 1803, Isim = "HONAZ", SehirID = 20 });
            ilceler.Add(new Ilce() { ID = 1774, Isim = "BEKİLLİ", SehirID = 20 });
            ilceler.Add(new Ilce() { ID = 1769, Isim = "BABADAĞ", SehirID = 20 });
            ilceler.Add(new Ilce() { ID = 1670, Isim = "TAVAS", SehirID = 20 });
            ilceler.Add(new Ilce() { ID = 1597, Isim = "SARAYKÖY", SehirID = 20 });
            ilceler.Add(new Ilce() { ID = 1426, Isim = "KALE", SehirID = 20 });
            ilceler.Add(new Ilce() { ID = 1371, Isim = "GÜNEY", SehirID = 20 });
            ilceler.Add(new Ilce() { ID = 1271, Isim = "MERKEZ", SehirID = 20 });
            ilceler.Add(new Ilce() { ID = 1257, Isim = "ÇİVRİL", SehirID = 20 });
            ilceler.Add(new Ilce() { ID = 1233, Isim = "ÇARDAK", SehirID = 20 });
            ilceler.Add(new Ilce() { ID = 1226, Isim = "ÇAMELİ", SehirID = 20 });
            ilceler.Add(new Ilce() { ID = 1224, Isim = "ÇAL", SehirID = 20 });
            ilceler.Add(new Ilce() { ID = 1214, Isim = "BULDAN", SehirID = 20 });
            ilceler.Add(new Ilce() { ID = 1102, Isim = "ACIPAYAM", SehirID = 20 });
            ilceler.Add(new Ilce() { ID = 99126, Isim = "Diyarbakır Havalimanı", SehirID = 21 });
            ilceler.Add(new Ilce() { ID = 2043, Isim = "YENİŞEHİR", SehirID = 21 });
            ilceler.Add(new Ilce() { ID = 2042, Isim = "SUR", SehirID = 21 });
            ilceler.Add(new Ilce() { ID = 2041, Isim = "KAYAPINAR", SehirID = 21 });
            ilceler.Add(new Ilce() { ID = 2040, Isim = "BAĞLAR", SehirID = 21 });
            ilceler.Add(new Ilce() { ID = 1962, Isim = "KOCAKÖY", SehirID = 21 });
            ilceler.Add(new Ilce() { ID = 1791, Isim = "EĞİL", SehirID = 21 });
            ilceler.Add(new Ilce() { ID = 1624, Isim = "SİLVAN", SehirID = 21 });
            ilceler.Add(new Ilce() { ID = 1504, Isim = "LİCE", SehirID = 21 });
            ilceler.Add(new Ilce() { ID = 1490, Isim = "KULP", SehirID = 21 });
            ilceler.Add(new Ilce() { ID = 1389, Isim = "HAZRO", SehirID = 21 });
            ilceler.Add(new Ilce() { ID = 1381, Isim = "HANİ", SehirID = 21 });
            ilceler.Add(new Ilce() { ID = 1315, Isim = "ERGANİ", SehirID = 21 });
            ilceler.Add(new Ilce() { ID = 1284, Isim = "MERKEZ", SehirID = 21 });
            ilceler.Add(new Ilce() { ID = 1278, Isim = "DİCLE", SehirID = 21 });
            ilceler.Add(new Ilce() { ID = 1263, Isim = "ÇÜNGÜŞ", SehirID = 21 });
            ilceler.Add(new Ilce() { ID = 1253, Isim = "ÇINAR", SehirID = 21 });
            ilceler.Add(new Ilce() { ID = 1249, Isim = "ÇERMİK", SehirID = 21 });
            ilceler.Add(new Ilce() { ID = 1195, Isim = "BİSMİL", SehirID = 21 });
            ilceler.Add(new Ilce() { ID = 1988, Isim = "SÜLOĞLU", SehirID = 22 });
            ilceler.Add(new Ilce() { ID = 1705, Isim = "UZUNKÖPRÜ", SehirID = 22 });
            ilceler.Add(new Ilce() { ID = 1523, Isim = "MERİÇ", SehirID = 22 });
            ilceler.Add(new Ilce() { ID = 1502, Isim = "LALAPAŞA", SehirID = 22 });
            ilceler.Add(new Ilce() { ID = 1464, Isim = "KEŞAN", SehirID = 22 });
            ilceler.Add(new Ilce() { ID = 1412, Isim = "İPSALA", SehirID = 22 });
            ilceler.Add(new Ilce() { ID = 1385, Isim = "HAVSA", SehirID = 22 });
            ilceler.Add(new Ilce() { ID = 1307, Isim = "ENEZ", SehirID = 22 });
            ilceler.Add(new Ilce() { ID = 1295, Isim = "MERKEZ", SehirID = 22 });
            ilceler.Add(new Ilce() { ID = 99144, Isim = "Elazığ Havalimanı", SehirID = 23 });
            ilceler.Add(new Ilce() { ID = 1873, Isim = "ALACAKAYA", SehirID = 23 });
            ilceler.Add(new Ilce() { ID = 1820, Isim = "KOVANCILAR", SehirID = 23 });
            ilceler.Add(new Ilce() { ID = 1762, Isim = "ARICAK", SehirID = 23 });
            ilceler.Add(new Ilce() { ID = 1631, Isim = "SİVRİCE", SehirID = 23 });
            ilceler.Add(new Ilce() { ID = 1566, Isim = "PALU", SehirID = 23 });
            ilceler.Add(new Ilce() { ID = 1506, Isim = "MADEN", SehirID = 23 });
            ilceler.Add(new Ilce() { ID = 1455, Isim = "KEBAN", SehirID = 23 });
            ilceler.Add(new Ilce() { ID = 1438, Isim = "KARAKOÇAN", SehirID = 23 });
            ilceler.Add(new Ilce() { ID = 1298, Isim = "MERKEZ", SehirID = 23 });
            ilceler.Add(new Ilce() { ID = 1173, Isim = "BASKİL", SehirID = 23 });
            ilceler.Add(new Ilce() { ID = 1110, Isim = "AĞIN", SehirID = 23 });
            ilceler.Add(new Ilce() { ID = 99109, Isim = "Erzincan Havalimanı", SehirID = 24 });
            ilceler.Add(new Ilce() { ID = 1977, Isim = "OTLUKBELİ", SehirID = 24 });
            ilceler.Add(new Ilce() { ID = 1853, Isim = "ÜZÜMLÜ", SehirID = 24 });
            ilceler.Add(new Ilce() { ID = 1675, Isim = "TERCAN", SehirID = 24 });
            ilceler.Add(new Ilce() { ID = 1583, Isim = "REFAHİYE", SehirID = 24 });
            ilceler.Add(new Ilce() { ID = 1460, Isim = "KEMALİYE", SehirID = 24 });
            ilceler.Add(new Ilce() { ID = 1459, Isim = "KEMAH", SehirID = 24 });
            ilceler.Add(new Ilce() { ID = 1406, Isim = "İLİÇ", SehirID = 24 });
            ilceler.Add(new Ilce() { ID = 1318, Isim = "MERKEZ", SehirID = 24 });
            ilceler.Add(new Ilce() { ID = 1243, Isim = "ÇAYIRLI", SehirID = 24 });
            ilceler.Add(new Ilce() { ID = 99100, Isim = "Erzurum Havalimanı", SehirID = 25 });
            ilceler.Add(new Ilce() { ID = 2045, Isim = "YAKUTİYE", SehirID = 25 });
            ilceler.Add(new Ilce() { ID = 2044, Isim = "PALANDÖKEN", SehirID = 25 });
            ilceler.Add(new Ilce() { ID = 1967, Isim = "KÖPRÜKÖY", SehirID = 25 });
            ilceler.Add(new Ilce() { ID = 1945, Isim = "AZİZİYE", SehirID = 25 });
            ilceler.Add(new Ilce() { ID = 1865, Isim = "PAZARYOLU", SehirID = 25 });
            ilceler.Add(new Ilce() { ID = 1851, Isim = "UZUNDERE", SehirID = 25 });
            ilceler.Add(new Ilce() { ID = 1812, Isim = "KARAÇOBAN", SehirID = 25 });
            ilceler.Add(new Ilce() { ID = 1683, Isim = "TORTUM", SehirID = 25 });
            ilceler.Add(new Ilce() { ID = 1674, Isim = "TEKMAN", SehirID = 25 });
            ilceler.Add(new Ilce() { ID = 1657, Isim = "ŞENKAYA", SehirID = 25 });
            ilceler.Add(new Ilce() { ID = 1567, Isim = "PASİNLER", SehirID = 25 });
            ilceler.Add(new Ilce() { ID = 1551, Isim = "OLUR", SehirID = 25 });
            ilceler.Add(new Ilce() { ID = 1550, Isim = "OLTU", SehirID = 25 });
            ilceler.Add(new Ilce() { ID = 1540, Isim = "NARMAN", SehirID = 25 });
            ilceler.Add(new Ilce() { ID = 1444, Isim = "KARAYAZI", SehirID = 25 });
            ilceler.Add(new Ilce() { ID = 1416, Isim = "İSPİR", SehirID = 25 });
            ilceler.Add(new Ilce() { ID = 1396, Isim = "HORASAN", SehirID = 25 });
            ilceler.Add(new Ilce() { ID = 1392, Isim = "HINIS", SehirID = 25 });
            ilceler.Add(new Ilce() { ID = 1319, Isim = "MERKEZ", SehirID = 25 });
            ilceler.Add(new Ilce() { ID = 1235, Isim = "ÇAT", SehirID = 25 });
            ilceler.Add(new Ilce() { ID = 1153, Isim = "AŞKALE", SehirID = 25 });
            ilceler.Add(new Ilce() { ID = 99162, Isim = "Eskişehir Anadolu Havalimanı", SehirID = 26 });
            ilceler.Add(new Ilce() { ID = 2047, Isim = "TEPEBAŞI", SehirID = 26 });
            ilceler.Add(new Ilce() { ID = 2046, Isim = "ODUNPAZARI", SehirID = 26 });
            ilceler.Add(new Ilce() { ID = 1973, Isim = "MİHALGAZİ", SehirID = 26 });
            ilceler.Add(new Ilce() { ID = 1939, Isim = "HAN", SehirID = 26 });
            ilceler.Add(new Ilce() { ID = 1934, Isim = "GÜNYÜZÜ", SehirID = 26 });
            ilceler.Add(new Ilce() { ID = 1808, Isim = "İNÖNÜ", SehirID = 26 });
            ilceler.Add(new Ilce() { ID = 1777, Isim = "BEYLİKOVA", SehirID = 26 });
            ilceler.Add(new Ilce() { ID = 1759, Isim = "ALPU", SehirID = 26 });
            ilceler.Add(new Ilce() { ID = 1632, Isim = "SİVRİHİSAR", SehirID = 26 });
            ilceler.Add(new Ilce() { ID = 1618, Isim = "SEYİTGAZİ", SehirID = 26 });
            ilceler.Add(new Ilce() { ID = 1599, Isim = "SARICAKAYA", SehirID = 26 });
            ilceler.Add(new Ilce() { ID = 1527, Isim = "MİHALIÇÇIK", SehirID = 26 });
            ilceler.Add(new Ilce() { ID = 1508, Isim = "MAHMUDİYE", SehirID = 26 });
            ilceler.Add(new Ilce() { ID = 1322, Isim = "MERKEZ", SehirID = 26 });
            ilceler.Add(new Ilce() { ID = 1255, Isim = "ÇİFTELER", SehirID = 26 });
            ilceler.Add(new Ilce() { ID = 99101, Isim = "Gaziantep Havalimanı", SehirID = 27 });
            ilceler.Add(new Ilce() { ID = 2700, Isim = "MERKEZ", SehirID = 27 });
            ilceler.Add(new Ilce() { ID = 1974, Isim = "NURDAĞI", SehirID = 27 });
            ilceler.Add(new Ilce() { ID = 1956, Isim = "KARKAMIŞ", SehirID = 27 });
            ilceler.Add(new Ilce() { ID = 1844, Isim = "ŞEHİTKAMİL", SehirID = 27 });
            ilceler.Add(new Ilce() { ID = 1841, Isim = "ŞAHİNBEY", SehirID = 27 });
            ilceler.Add(new Ilce() { ID = 1720, Isim = "YAVUZELİ", SehirID = 27 });
            ilceler.Add(new Ilce() { ID = 1549, Isim = "OĞUZELİ", SehirID = 27 });
            ilceler.Add(new Ilce() { ID = 1546, Isim = "NİZİP", SehirID = 27 });
            ilceler.Add(new Ilce() { ID = 1415, Isim = "İSLAHİYE", SehirID = 27 });
            ilceler.Add(new Ilce() { ID = 1139, Isim = "ARABAN", SehirID = 27 });
            ilceler.Add(new Ilce() { ID = 1930, Isim = "GÜCE", SehirID = 28 });
            ilceler.Add(new Ilce() { ID = 1912, Isim = "DOĞANKENT", SehirID = 28 });
            ilceler.Add(new Ilce() { ID = 1894, Isim = "ÇANAKÇI", SehirID = 28 });
            ilceler.Add(new Ilce() { ID = 1893, Isim = "ÇAMOLUK", SehirID = 28 });
            ilceler.Add(new Ilce() { ID = 1854, Isim = "YAĞLIDERE", SehirID = 28 });
            ilceler.Add(new Ilce() { ID = 1837, Isim = "PİRAZİZ", SehirID = 28 });
            ilceler.Add(new Ilce() { ID = 1678, Isim = "TİREBOLU", SehirID = 28 });
            ilceler.Add(new Ilce() { ID = 1654, Isim = "ŞEBİNKARAHİSAR", SehirID = 28 });
            ilceler.Add(new Ilce() { ID = 1465, Isim = "KEŞAP", SehirID = 28 });
            ilceler.Add(new Ilce() { ID = 1361, Isim = "GÖRELE", SehirID = 28 });
            ilceler.Add(new Ilce() { ID = 1352, Isim = "MERKEZ", SehirID = 28 });
            ilceler.Add(new Ilce() { ID = 1324, Isim = "EYNESİL", SehirID = 28 });
            ilceler.Add(new Ilce() { ID = 1320, Isim = "ESPİYE", SehirID = 28 });
            ilceler.Add(new Ilce() { ID = 1272, Isim = "DERELİ", SehirID = 28 });
            ilceler.Add(new Ilce() { ID = 1212, Isim = "BULANCAK", SehirID = 28 });
            ilceler.Add(new Ilce() { ID = 1133, Isim = "ALUCRA", SehirID = 28 });
            ilceler.Add(new Ilce() { ID = 1971, Isim = "KÜRTÜN", SehirID = 29 });
            ilceler.Add(new Ilce() { ID = 1822, Isim = "KÖSE", SehirID = 29 });
            ilceler.Add(new Ilce() { ID = 1684, Isim = "TORUL", SehirID = 29 });
            ilceler.Add(new Ilce() { ID = 1660, Isim = "ŞİRAN", SehirID = 29 });
            ilceler.Add(new Ilce() { ID = 1458, Isim = "KELKİT", SehirID = 29 });
            ilceler.Add(new Ilce() { ID = 1369, Isim = "MERKEZ", SehirID = 29 });
            ilceler.Add(new Ilce() { ID = 99110, Isim = "Hakkâri Yüksekova Selahaddin Eyyubi Havalimanı", SehirID = 30 });
            ilceler.Add(new Ilce() { ID = 1737, Isim = "YÜKSEKOVA", SehirID = 30 });
            ilceler.Add(new Ilce() { ID = 1656, Isim = "ŞEMDİNLİ", SehirID = 30 });
            ilceler.Add(new Ilce() { ID = 1377, Isim = "MERKEZ", SehirID = 30 });
            ilceler.Add(new Ilce() { ID = 1261, Isim = "ÇUKURCA", SehirID = 30 });
            ilceler.Add(new Ilce() { ID = 99161, Isim = "Hatay Havalimanı", SehirID = 31 });
            ilceler.Add(new Ilce() { ID = 2083, Isim = "PAYAS", SehirID = 31 });
            ilceler.Add(new Ilce() { ID = 2082, Isim = "DEFNE", SehirID = 31 });
            ilceler.Add(new Ilce() { ID = 2081, Isim = "ARSUZ", SehirID = 31 });
            ilceler.Add(new Ilce() { ID = 2080, Isim = "ANTAKYA", SehirID = 31 });
            ilceler.Add(new Ilce() { ID = 1970, Isim = "KUMLU", SehirID = 31 });
            ilceler.Add(new Ilce() { ID = 1887, Isim = "BELEN", SehirID = 31 });
            ilceler.Add(new Ilce() { ID = 1792, Isim = "ERZİN", SehirID = 31 });
            ilceler.Add(new Ilce() { ID = 1721, Isim = "YAYLADAĞI", SehirID = 31 });
            ilceler.Add(new Ilce() { ID = 1591, Isim = "SAMANDAĞ", SehirID = 31 });
            ilceler.Add(new Ilce() { ID = 1585, Isim = "REYHANLI", SehirID = 31 });
            ilceler.Add(new Ilce() { ID = 1468, Isim = "KIRIKHAN", SehirID = 31 });
            ilceler.Add(new Ilce() { ID = 1413, Isim = "İSKENDERUN", SehirID = 31 });
            ilceler.Add(new Ilce() { ID = 1383, Isim = "MERKEZ", SehirID = 31 });
            ilceler.Add(new Ilce() { ID = 1382, Isim = "HASSA", SehirID = 31 });
            ilceler.Add(new Ilce() { ID = 1289, Isim = "DÖRTYOL", SehirID = 31 });
            ilceler.Add(new Ilce() { ID = 1131, Isim = "ALTINÖZÜ", SehirID = 31 });
            ilceler.Add(new Ilce() { ID = 99112, Isim = "Isparta Süleyman Demirel Havalimanı", SehirID = 32 });
            ilceler.Add(new Ilce() { ID = 2001, Isim = "YENİŞARBADEMLİ", SehirID = 32 });
            ilceler.Add(new Ilce() { ID = 1929, Isim = "GÖNEN", SehirID = 32 });
            ilceler.Add(new Ilce() { ID = 1755, Isim = "AKSU", SehirID = 32 });
            ilceler.Add(new Ilce() { ID = 1717, Isim = "YALVAÇ", SehirID = 32 });
            ilceler.Add(new Ilce() { ID = 1699, Isim = "ULUBORLU", SehirID = 32 });
            ilceler.Add(new Ilce() { ID = 1651, Isim = "ŞARKİKARAAĞAÇ", SehirID = 32 });
            ilceler.Add(new Ilce() { ID = 1648, Isim = "SÜTÇÜLER", SehirID = 32 });
            ilceler.Add(new Ilce() { ID = 1615, Isim = "SENİRKENT", SehirID = 32 });
            ilceler.Add(new Ilce() { ID = 1456, Isim = "KEÇİBORLU", SehirID = 32 });
            ilceler.Add(new Ilce() { ID = 1401, Isim = "MERKEZ", SehirID = 32 });
            ilceler.Add(new Ilce() { ID = 1341, Isim = "GELENDOST", SehirID = 32 });
            ilceler.Add(new Ilce() { ID = 1297, Isim = "EĞİRDİR", SehirID = 32 });
            ilceler.Add(new Ilce() { ID = 1154, Isim = "ATABEY", SehirID = 32 });
            ilceler.Add(new Ilce() { ID = 2067, Isim = "YENİŞEHİR", SehirID = 33 });
            ilceler.Add(new Ilce() { ID = 2066, Isim = "TOROSLAR", SehirID = 33 });
            ilceler.Add(new Ilce() { ID = 2065, Isim = "MEZİTLİ", SehirID = 33 });
            ilceler.Add(new Ilce() { ID = 2064, Isim = "AKDENİZ", SehirID = 33 });
            ilceler.Add(new Ilce() { ID = 1892, Isim = "ÇAMLIYAYLA", SehirID = 33 });
            ilceler.Add(new Ilce() { ID = 1779, Isim = "BOZYAZI", SehirID = 33 });
            ilceler.Add(new Ilce() { ID = 1766, Isim = "AYDINCIK", SehirID = 33 });
            ilceler.Add(new Ilce() { ID = 1665, Isim = "TARSUS", SehirID = 33 });
            ilceler.Add(new Ilce() { ID = 1621, Isim = "SİLİFKE", SehirID = 33 });
            ilceler.Add(new Ilce() { ID = 1536, Isim = "MUT", SehirID = 33 });
            ilceler.Add(new Ilce() { ID = 1402, Isim = "MERKEZ", SehirID = 33 });
            ilceler.Add(new Ilce() { ID = 1366, Isim = "GÜLNAR", SehirID = 33 });
            ilceler.Add(new Ilce() { ID = 1311, Isim = "ERDEMLİ", SehirID = 33 });
            ilceler.Add(new Ilce() { ID = 1135, Isim = "ANAMUR", SehirID = 33 });
            ilceler.Add(new Ilce() { ID = 99157, Isim = "İstanbul Havalimanı", SehirID = 34 });
            ilceler.Add(new Ilce() { ID = 99136, Isim = "Atatürk Havalimanı", SehirID = 34 });
            ilceler.Add(new Ilce() { ID = 99102, Isim = "Sabiha Gökçen Havalimanı", SehirID = 34 });
            ilceler.Add(new Ilce() { ID = 2055, Isim = "SULTANGAZİ", SehirID = 34 });
            ilceler.Add(new Ilce() { ID = 2054, Isim = "SANCAKTEPE", SehirID = 34 });
            ilceler.Add(new Ilce() { ID = 2053, Isim = "ESENYURT", SehirID = 34 });
            ilceler.Add(new Ilce() { ID = 2052, Isim = "ÇEKMEKÖY", SehirID = 34 });
            ilceler.Add(new Ilce() { ID = 2051, Isim = "BEYLİKDÜZÜ", SehirID = 34 });
            ilceler.Add(new Ilce() { ID = 2050, Isim = "BAŞAKŞEHİR", SehirID = 34 });
            ilceler.Add(new Ilce() { ID = 2049, Isim = "ATAŞEHİR", SehirID = 34 });
            ilceler.Add(new Ilce() { ID = 2048, Isim = "ARNAVUTKÖY", SehirID = 34 });
            ilceler.Add(new Ilce() { ID = 2016, Isim = "ESENLER", SehirID = 34 });
            ilceler.Add(new Ilce() { ID = 2015, Isim = "TUZLA", SehirID = 34 });
            ilceler.Add(new Ilce() { ID = 2014, Isim = "SULTANBEYLİ", SehirID = 34 });
            ilceler.Add(new Ilce() { ID = 2012, Isim = "MALTEPE", SehirID = 34 });
            ilceler.Add(new Ilce() { ID = 2010, Isim = "GÜNGÖREN", SehirID = 34 });
            ilceler.Add(new Ilce() { ID = 2005, Isim = "BAHÇELİEVLER", SehirID = 34 });
            ilceler.Add(new Ilce() { ID = 2004, Isim = "BAĞCILAR", SehirID = 34 });
            ilceler.Add(new Ilce() { ID = 2003, Isim = "AVCILAR", SehirID = 34 });
            ilceler.Add(new Ilce() { ID = 1886, Isim = "BAYRAMPAŞA", SehirID = 34 });
            ilceler.Add(new Ilce() { ID = 1852, Isim = "ÜMRANİYE", SehirID = 34 });
            ilceler.Add(new Ilce() { ID = 1835, Isim = "PENDİK", SehirID = 34 });
            ilceler.Add(new Ilce() { ID = 1823, Isim = "KÜÇÜKÇEKMECE", SehirID = 34 });
            ilceler.Add(new Ilce() { ID = 1810, Isim = "KAĞITHANE", SehirID = 34 });
            ilceler.Add(new Ilce() { ID = 1782, Isim = "BÜYÜKÇEKMECE", SehirID = 34 });
            ilceler.Add(new Ilce() { ID = 1739, Isim = "ZEYTİNBURNU", SehirID = 34 });
            ilceler.Add(new Ilce() { ID = 1708, Isim = "ÜSKÜDAR", SehirID = 34 });
            ilceler.Add(new Ilce() { ID = 1663, Isim = "ŞİŞLİ", SehirID = 34 });
            ilceler.Add(new Ilce() { ID = 1659, Isim = "ŞİLE", SehirID = 34 });
            ilceler.Add(new Ilce() { ID = 1622, Isim = "SİLİVRİ", SehirID = 34 });
            ilceler.Add(new Ilce() { ID = 1604, Isim = "SARIYER", SehirID = 34 });
            ilceler.Add(new Ilce() { ID = 1449, Isim = "KARTAL", SehirID = 34 });
            ilceler.Add(new Ilce() { ID = 1421, Isim = "KADIKÖY", SehirID = 34 });
            ilceler.Add(new Ilce() { ID = 1336, Isim = "GAZİOSMANPAŞA", SehirID = 34 });
            ilceler.Add(new Ilce() { ID = 1327, Isim = "FATİH", SehirID = 34 });
            ilceler.Add(new Ilce() { ID = 1325, Isim = "EYÜPSULTAN", SehirID = 34 });
            ilceler.Add(new Ilce() { ID = 1305, Isim = "EMİNÖNÜ", SehirID = 34 });
            ilceler.Add(new Ilce() { ID = 1237, Isim = "ÇATALCA", SehirID = 34 });
            ilceler.Add(new Ilce() { ID = 1186, Isim = "BEYOĞLU", SehirID = 34 });
            ilceler.Add(new Ilce() { ID = 1185, Isim = "BEYKOZ", SehirID = 34 });
            ilceler.Add(new Ilce() { ID = 1183, Isim = "BEŞİKTAŞ", SehirID = 34 });
            ilceler.Add(new Ilce() { ID = 1166, Isim = "BAKIRKÖY", SehirID = 34 });
            ilceler.Add(new Ilce() { ID = 1103, Isim = "ADALAR", SehirID = 34 });
            ilceler.Add(new Ilce() { ID = 99164, Isim = "Adnan Menderes Havalimanı", SehirID = 35 });
            ilceler.Add(new Ilce() { ID = 2057, Isim = "KARABAĞLAR", SehirID = 35 });
            ilceler.Add(new Ilce() { ID = 2056, Isim = "BAYRAKLI", SehirID = 35 });
            ilceler.Add(new Ilce() { ID = 2018, Isim = "GÜZELBAHÇE", SehirID = 35 });
            ilceler.Add(new Ilce() { ID = 2013, Isim = "NARLIDERE", SehirID = 35 });
            ilceler.Add(new Ilce() { ID = 2009, Isim = "GAZİEMİR", SehirID = 35 });
            ilceler.Add(new Ilce() { ID = 2007, Isim = "ÇİĞLİ", SehirID = 35 });
            ilceler.Add(new Ilce() { ID = 2006, Isim = "BALÇOVA", SehirID = 35 });
            ilceler.Add(new Ilce() { ID = 1826, Isim = "MENDERES", SehirID = 35 });
            ilceler.Add(new Ilce() { ID = 1819, Isim = "KONAK", SehirID = 35 });
            ilceler.Add(new Ilce() { ID = 1780, Isim = "BUCA", SehirID = 35 });
            ilceler.Add(new Ilce() { ID = 1776, Isim = "BEYDAĞ", SehirID = 35 });
            ilceler.Add(new Ilce() { ID = 1703, Isim = "URLA", SehirID = 35 });
            ilceler.Add(new Ilce() { ID = 1682, Isim = "TORBALI", SehirID = 35 });
            ilceler.Add(new Ilce() { ID = 1677, Isim = "TİRE", SehirID = 35 });
            ilceler.Add(new Ilce() { ID = 1612, Isim = "SELÇUK", SehirID = 35 });
            ilceler.Add(new Ilce() { ID = 1611, Isim = "SEFERİHİSAR", SehirID = 35 });
            ilceler.Add(new Ilce() { ID = 1563, Isim = "ÖDEMİŞ", SehirID = 35 });
            ilceler.Add(new Ilce() { ID = 1521, Isim = "MENEMEN", SehirID = 35 });
            ilceler.Add(new Ilce() { ID = 1477, Isim = "KİRAZ", SehirID = 35 });
            ilceler.Add(new Ilce() { ID = 1467, Isim = "KINIK", SehirID = 35 });
            ilceler.Add(new Ilce() { ID = 1461, Isim = "KEMALPAŞA", SehirID = 35 });
            ilceler.Add(new Ilce() { ID = 1448, Isim = "KARŞIYAKA", SehirID = 35 });
            ilceler.Add(new Ilce() { ID = 1432, Isim = "KARABURUN", SehirID = 35 });
            ilceler.Add(new Ilce() { ID = 1334, Isim = "FOÇA", SehirID = 35 });
            ilceler.Add(new Ilce() { ID = 1280, Isim = "DİKİLİ", SehirID = 35 });
            ilceler.Add(new Ilce() { ID = 1251, Isim = "ÇEŞME", SehirID = 35 });
            ilceler.Add(new Ilce() { ID = 1203, Isim = "BORNOVA", SehirID = 35 });
            ilceler.Add(new Ilce() { ID = 1181, Isim = "BERGAMA", SehirID = 35 });
            ilceler.Add(new Ilce() { ID = 1178, Isim = "BAYINDIR", SehirID = 35 });
            ilceler.Add(new Ilce() { ID = 1128, Isim = "ALİAĞA", SehirID = 35 });
            ilceler.Add(new Ilce() { ID = 99113, Isim = "Kars Harakani Havalimanı", SehirID = 36 });
            ilceler.Add(new Ilce() { ID = 1756, Isim = "AKYAKA", SehirID = 36 });
            ilceler.Add(new Ilce() { ID = 1645, Isim = "SUSUZ", SehirID = 36 });
            ilceler.Add(new Ilce() { ID = 1614, Isim = "SELİM", SehirID = 36 });
            ilceler.Add(new Ilce() { ID = 1601, Isim = "SARIKAMIŞ", SehirID = 36 });
            ilceler.Add(new Ilce() { ID = 1447, Isim = "MERKEZ", SehirID = 36 });
            ilceler.Add(new Ilce() { ID = 1424, Isim = "KAĞIZMAN", SehirID = 36 });
            ilceler.Add(new Ilce() { ID = 1279, Isim = "DİGOR", SehirID = 36 });
            ilceler.Add(new Ilce() { ID = 1149, Isim = "ARPAÇAY", SehirID = 36 });
            ilceler.Add(new Ilce() { ID = 99154, Isim = "Kastamonu Havalimanı", SehirID = 37 });
            ilceler.Add(new Ilce() { ID = 1984, Isim = "SEYDİLER", SehirID = 37 });
            ilceler.Add(new Ilce() { ID = 1940, Isim = "HANÖNÜ", SehirID = 37 });
            ilceler.Add(new Ilce() { ID = 1915, Isim = "DOĞANYURT", SehirID = 37 });
            ilceler.Add(new Ilce() { ID = 1867, Isim = "AĞLI", SehirID = 37 });
            ilceler.Add(new Ilce() { ID = 1845, Isim = "ŞENPAZAR", SehirID = 37 });
            ilceler.Add(new Ilce() { ID = 1836, Isim = "PINARBAŞI", SehirID = 37 });
            ilceler.Add(new Ilce() { ID = 1805, Isim = "İHSANGAZİ", SehirID = 37 });
            ilceler.Add(new Ilce() { ID = 1685, Isim = "TOSYA", SehirID = 37 });
            ilceler.Add(new Ilce() { ID = 1666, Isim = "TAŞKÖPRÜ", SehirID = 37 });
            ilceler.Add(new Ilce() { ID = 1499, Isim = "KÜRE", SehirID = 37 });
            ilceler.Add(new Ilce() { ID = 1450, Isim = "MERKEZ", SehirID = 37 });
            ilceler.Add(new Ilce() { ID = 1410, Isim = "İNEBOLU", SehirID = 37 });
            ilceler.Add(new Ilce() { ID = 1277, Isim = "DEVREKANİ", SehirID = 37 });
            ilceler.Add(new Ilce() { ID = 1264, Isim = "DADAY", SehirID = 37 });
            ilceler.Add(new Ilce() { ID = 1238, Isim = "ÇATALZEYTİN", SehirID = 37 });
            ilceler.Add(new Ilce() { ID = 1221, Isim = "CİDE", SehirID = 37 });
            ilceler.Add(new Ilce() { ID = 1208, Isim = "BOZKURT", SehirID = 37 });
            ilceler.Add(new Ilce() { ID = 1162, Isim = "AZDAVAY", SehirID = 37 });
            ilceler.Add(new Ilce() { ID = 1140, Isim = "ARAÇ", SehirID = 37 });
            ilceler.Add(new Ilce() { ID = 1101, Isim = "ABANA", SehirID = 37 });
            ilceler.Add(new Ilce() { ID = 99103, Isim = "Erkilet Havalimanı", SehirID = 38 });
            ilceler.Add(new Ilce() { ID = 1978, Isim = "ÖZVATAN", SehirID = 38 });
            ilceler.Add(new Ilce() { ID = 1936, Isim = "HACILAR", SehirID = 38 });
            ilceler.Add(new Ilce() { ID = 1864, Isim = "MELİKGAZİ", SehirID = 38 });
            ilceler.Add(new Ilce() { ID = 1863, Isim = "KOCASİNAN", SehirID = 38 });
            ilceler.Add(new Ilce() { ID = 1846, Isim = "TALAS", SehirID = 38 });
            ilceler.Add(new Ilce() { ID = 1752, Isim = "AKKIŞLA", SehirID = 38 });
            ilceler.Add(new Ilce() { ID = 1727, Isim = "YEŞİLHİSAR", SehirID = 38 });
            ilceler.Add(new Ilce() { ID = 1715, Isim = "YAHYALI", SehirID = 38 });
            ilceler.Add(new Ilce() { ID = 1680, Isim = "TOMARZA", SehirID = 38 });
            ilceler.Add(new Ilce() { ID = 1605, Isim = "SARIZ", SehirID = 38 });
            ilceler.Add(new Ilce() { ID = 1603, Isim = "SARIOĞLAN", SehirID = 38 });
            ilceler.Add(new Ilce() { ID = 1576, Isim = "PINARBAŞI", SehirID = 38 });
            ilceler.Add(new Ilce() { ID = 1409, Isim = "İNCESU", SehirID = 38 });
            ilceler.Add(new Ilce() { ID = 1330, Isim = "FELAHİYE", SehirID = 38 });
            ilceler.Add(new Ilce() { ID = 1275, Isim = "DEVELİ", SehirID = 38 });
            ilceler.Add(new Ilce() { ID = 1218, Isim = "BÜNYAN", SehirID = 38 });
            ilceler.Add(new Ilce() { ID = 1714, Isim = "VİZE", SehirID = 39 });
            ilceler.Add(new Ilce() { ID = 1577, Isim = "PINARHİSAR", SehirID = 39 });
            ilceler.Add(new Ilce() { ID = 1572, Isim = "PEHLİVANKÖY", SehirID = 39 });
            ilceler.Add(new Ilce() { ID = 1505, Isim = "LÜLEBURGAZ", SehirID = 39 });
            ilceler.Add(new Ilce() { ID = 1480, Isim = "KOFÇAZ", SehirID = 39 });
            ilceler.Add(new Ilce() { ID = 1471, Isim = "MERKEZ", SehirID = 39 });
            ilceler.Add(new Ilce() { ID = 1270, Isim = "DEMİRKÖY", SehirID = 39 });
            ilceler.Add(new Ilce() { ID = 1163, Isim = "BABAESKİ", SehirID = 39 });
            ilceler.Add(new Ilce() { ID = 1890, Isim = "BOZTEPE", SehirID = 40 });
            ilceler.Add(new Ilce() { ID = 1869, Isim = "AKÇAKENT", SehirID = 40 });
            ilceler.Add(new Ilce() { ID = 1754, Isim = "AKPINAR", SehirID = 40 });
            ilceler.Add(new Ilce() { ID = 1529, Isim = "MUCUR", SehirID = 40 });
            ilceler.Add(new Ilce() { ID = 1472, Isim = "MERKEZ", SehirID = 40 });
            ilceler.Add(new Ilce() { ID = 1429, Isim = "KAMAN", SehirID = 40 });
            ilceler.Add(new Ilce() { ID = 1254, Isim = "ÇİÇEKDAĞI", SehirID = 40 });
            ilceler.Add(new Ilce() { ID = 99155, Isim = "Cengiz Topel Havalimanı", SehirID = 41 });
            ilceler.Add(new Ilce() { ID = 2063, Isim = "KARTEPE", SehirID = 41 });
            ilceler.Add(new Ilce() { ID = 2062, Isim = "İZMİT", SehirID = 41 });
            ilceler.Add(new Ilce() { ID = 2061, Isim = "DİLOVASI", SehirID = 41 });
            ilceler.Add(new Ilce() { ID = 2060, Isim = "DARICA", SehirID = 41 });
            ilceler.Add(new Ilce() { ID = 2059, Isim = "ÇAYIROVA", SehirID = 41 });
            ilceler.Add(new Ilce() { ID = 2058, Isim = "BAŞİSKELE", SehirID = 41 });
            ilceler.Add(new Ilce() { ID = 2030, Isim = "DERİNCE", SehirID = 41 });
            ilceler.Add(new Ilce() { ID = 1821, Isim = "KÖRFEZ", SehirID = 41 });
            ilceler.Add(new Ilce() { ID = 1478, Isim = "MERKEZ", SehirID = 41 });
            ilceler.Add(new Ilce() { ID = 1440, Isim = "KARAMÜRSEL", SehirID = 41 });
            ilceler.Add(new Ilce() { ID = 1430, Isim = "KANDIRA", SehirID = 41 });
            ilceler.Add(new Ilce() { ID = 1355, Isim = "GÖLCÜK", SehirID = 41 });
            ilceler.Add(new Ilce() { ID = 1338, Isim = "GEBZE", SehirID = 41 });
            ilceler.Add(new Ilce() { ID = 99104, Isim = "Konya Havalimanı", SehirID = 42 });
            ilceler.Add(new Ilce() { ID = 1994, Isim = "YALIHÜYÜK", SehirID = 42 });
            ilceler.Add(new Ilce() { ID = 1990, Isim = "TUZLUKÇU", SehirID = 42 });
            ilceler.Add(new Ilce() { ID = 1937, Isim = "HALKAPINAR", SehirID = 42 });
            ilceler.Add(new Ilce() { ID = 1933, Isim = "GÜNEYSINIR", SehirID = 42 });
            ilceler.Add(new Ilce() { ID = 1920, Isim = "EMİRGAZİ", SehirID = 42 });
            ilceler.Add(new Ilce() { ID = 1907, Isim = "DERBENT", SehirID = 42 });
            ilceler.Add(new Ilce() { ID = 1902, Isim = "ÇELTİK", SehirID = 42 });
            ilceler.Add(new Ilce() { ID = 1868, Isim = "AHIRLI", SehirID = 42 });
            ilceler.Add(new Ilce() { ID = 1848, Isim = "TAŞKENT", SehirID = 42 });
            ilceler.Add(new Ilce() { ID = 1839, Isim = "SELÇUKLU", SehirID = 42 });
            ilceler.Add(new Ilce() { ID = 1827, Isim = "MERAM", SehirID = 42 });
            ilceler.Add(new Ilce() { ID = 1814, Isim = "KARATAY", SehirID = 42 });
            ilceler.Add(new Ilce() { ID = 1804, Isim = "HÜYÜK", SehirID = 42 });
            ilceler.Add(new Ilce() { ID = 1789, Isim = "DEREBUCAK", SehirID = 42 });
            ilceler.Add(new Ilce() { ID = 1760, Isim = "ALTINEKİN", SehirID = 42 });
            ilceler.Add(new Ilce() { ID = 1753, Isim = "AKÖREN", SehirID = 42 });
            ilceler.Add(new Ilce() { ID = 1735, Isim = "YUNAK", SehirID = 42 });
            ilceler.Add(new Ilce() { ID = 1617, Isim = "SEYDİŞEHİR", SehirID = 42 });
            ilceler.Add(new Ilce() { ID = 1598, Isim = "SARAYÖNÜ", SehirID = 42 });
            ilceler.Add(new Ilce() { ID = 1491, Isim = "KULU", SehirID = 42 });
            ilceler.Add(new Ilce() { ID = 1441, Isim = "KARAPINAR", SehirID = 42 });
            ilceler.Add(new Ilce() { ID = 1422, Isim = "KADINHANI", SehirID = 42 });
            ilceler.Add(new Ilce() { ID = 1400, Isim = "ILGIN", SehirID = 42 });
            ilceler.Add(new Ilce() { ID = 1375, Isim = "HADİM", SehirID = 42 });
            ilceler.Add(new Ilce() { ID = 1312, Isim = "EREĞLİ", SehirID = 42 });
            ilceler.Add(new Ilce() { ID = 1285, Isim = "DOĞANHİSAR", SehirID = 42 });
            ilceler.Add(new Ilce() { ID = 1262, Isim = "ÇUMRA", SehirID = 42 });
            ilceler.Add(new Ilce() { ID = 1222, Isim = "CİHANBEYLİ", SehirID = 42 });
            ilceler.Add(new Ilce() { ID = 1207, Isim = "BOZKIR", SehirID = 42 });
            ilceler.Add(new Ilce() { ID = 1188, Isim = "BEYŞEHİR", SehirID = 42 });
            ilceler.Add(new Ilce() { ID = 1122, Isim = "AKŞEHİR", SehirID = 42 });
            ilceler.Add(new Ilce() { ID = 99165, Isim = "Zafer Havalimanı", SehirID = 43 });
            ilceler.Add(new Ilce() { ID = 1979, Isim = "PAZARLAR", SehirID = 43 });
            ilceler.Add(new Ilce() { ID = 1898, Isim = "ÇAVDARHİSAR", SehirID = 43 });
            ilceler.Add(new Ilce() { ID = 1843, Isim = "ŞAPHANE", SehirID = 43 });
            ilceler.Add(new Ilce() { ID = 1802, Isim = "HİSARCIK", SehirID = 43 });
            ilceler.Add(new Ilce() { ID = 1790, Isim = "DUMLUPINAR", SehirID = 43 });
            ilceler.Add(new Ilce() { ID = 1764, Isim = "ASLANAPA", SehirID = 43 });
            ilceler.Add(new Ilce() { ID = 1671, Isim = "TAVŞANLI", SehirID = 43 });
            ilceler.Add(new Ilce() { ID = 1625, Isim = "SİMAV", SehirID = 43 });
            ilceler.Add(new Ilce() { ID = 1500, Isim = "MERKEZ", SehirID = 43 });
            ilceler.Add(new Ilce() { ID = 1339, Isim = "GEDİZ", SehirID = 43 });
            ilceler.Add(new Ilce() { ID = 1304, Isim = "EMET", SehirID = 43 });
            ilceler.Add(new Ilce() { ID = 1288, Isim = "DOMANİÇ", SehirID = 43 });
            ilceler.Add(new Ilce() { ID = 1132, Isim = "ALTINTAŞ", SehirID = 43 });
            ilceler.Add(new Ilce() { ID = 99137, Isim = "Erhaç Havalimanı", SehirID = 44 });
            ilceler.Add(new Ilce() { ID = 1995, Isim = "YAZIHAN", SehirID = 44 });
            ilceler.Add(new Ilce() { ID = 1969, Isim = "KULUNCAK", SehirID = 44 });
            ilceler.Add(new Ilce() { ID = 1953, Isim = "KALE", SehirID = 44 });
            ilceler.Add(new Ilce() { ID = 1914, Isim = "DOĞANYOL", SehirID = 44 });
            ilceler.Add(new Ilce() { ID = 1772, Isim = "BATTALGAZİ", SehirID = 44 });
            ilceler.Add(new Ilce() { ID = 1729, Isim = "YEŞİLYURT", SehirID = 44 });
            ilceler.Add(new Ilce() { ID = 1582, Isim = "PÜTÜRGE", SehirID = 44 });
            ilceler.Add(new Ilce() { ID = 1509, Isim = "MERKEZ", SehirID = 44 });
            ilceler.Add(new Ilce() { ID = 1390, Isim = "HEKİMHAN", SehirID = 44 });
            ilceler.Add(new Ilce() { ID = 1286, Isim = "DOĞANŞEHİR", SehirID = 44 });
            ilceler.Add(new Ilce() { ID = 1265, Isim = "DARENDE", SehirID = 44 });
            ilceler.Add(new Ilce() { ID = 1148, Isim = "ARGUVAN", SehirID = 44 });
            ilceler.Add(new Ilce() { ID = 1143, Isim = "ARAPGİR", SehirID = 44 });
            ilceler.Add(new Ilce() { ID = 1114, Isim = "AKÇADAĞ", SehirID = 44 });
            ilceler.Add(new Ilce() { ID = 2087, Isim = "YUNUSEMRE", SehirID = 45 });
            ilceler.Add(new Ilce() { ID = 2086, Isim = "ŞEHZADELER", SehirID = 45 });
            ilceler.Add(new Ilce() { ID = 1965, Isim = "KÖPRÜBAŞI", SehirID = 45 });
            ilceler.Add(new Ilce() { ID = 1793, Isim = "GÖLMARMARA", SehirID = 45 });
            ilceler.Add(new Ilce() { ID = 1751, Isim = "AHMETLİ", SehirID = 45 });
            ilceler.Add(new Ilce() { ID = 1689, Isim = "TURGUTLU", SehirID = 45 });
            ilceler.Add(new Ilce() { ID = 1634, Isim = "SOMA", SehirID = 45 });
            ilceler.Add(new Ilce() { ID = 1613, Isim = "SELENDİ", SehirID = 45 });
            ilceler.Add(new Ilce() { ID = 1606, Isim = "SARUHANLI", SehirID = 45 });
            ilceler.Add(new Ilce() { ID = 1600, Isim = "SARIGÖL", SehirID = 45 });
            ilceler.Add(new Ilce() { ID = 1590, Isim = "SALİHLİ", SehirID = 45 });
            ilceler.Add(new Ilce() { ID = 1513, Isim = "MERKEZ", SehirID = 45 });
            ilceler.Add(new Ilce() { ID = 1489, Isim = "KULA", SehirID = 45 });
            ilceler.Add(new Ilce() { ID = 1470, Isim = "KIRKAĞAÇ", SehirID = 45 });
            ilceler.Add(new Ilce() { ID = 1362, Isim = "GÖRDES", SehirID = 45 });
            ilceler.Add(new Ilce() { ID = 1269, Isim = "DEMİRCİ", SehirID = 45 });
            ilceler.Add(new Ilce() { ID = 1127, Isim = "ALAŞEHİR", SehirID = 45 });
            ilceler.Add(new Ilce() { ID = 1118, Isim = "AKHİSAR", SehirID = 45 });
            ilceler.Add(new Ilce() { ID = 99145, Isim = "Kahramanmaraş Havalimanı", SehirID = 46 });
            ilceler.Add(new Ilce() { ID = 2085, Isim = "ONİKİŞUBAT", SehirID = 46 });
            ilceler.Add(new Ilce() { ID = 2084, Isim = "DULKADİROĞLU", SehirID = 46 });
            ilceler.Add(new Ilce() { ID = 1975, Isim = "NURHAK", SehirID = 46 });
            ilceler.Add(new Ilce() { ID = 1919, Isim = "EKİNÖZÜ", SehirID = 46 });
            ilceler.Add(new Ilce() { ID = 1785, Isim = "ÇAĞLAYANCERİT", SehirID = 46 });
            ilceler.Add(new Ilce() { ID = 1694, Isim = "TÜRKOĞLU", SehirID = 46 });
            ilceler.Add(new Ilce() { ID = 1570, Isim = "PAZARCIK", SehirID = 46 });
            ilceler.Add(new Ilce() { ID = 1515, Isim = "MERKEZ", SehirID = 46 });
            ilceler.Add(new Ilce() { ID = 1353, Isim = "GÖKSUN", SehirID = 46 });
            ilceler.Add(new Ilce() { ID = 1299, Isim = "ELBİSTAN", SehirID = 46 });
            ilceler.Add(new Ilce() { ID = 1136, Isim = "ANDIRIN", SehirID = 46 });
            ilceler.Add(new Ilce() { ID = 1107, Isim = "AFŞİN", SehirID = 46 });
            ilceler.Add(new Ilce() { ID = 99114, Isim = "Mardin Havalimanı", SehirID = 47 });
            ilceler.Add(new Ilce() { ID = 2088, Isim = "ARTUKLU", SehirID = 47 });
            ilceler.Add(new Ilce() { ID = 2002, Isim = "YEŞİLLİ", SehirID = 47 });
            ilceler.Add(new Ilce() { ID = 1787, Isim = "DARGEÇİT", SehirID = 47 });
            ilceler.Add(new Ilce() { ID = 1609, Isim = "SAVUR", SehirID = 47 });
            ilceler.Add(new Ilce() { ID = 1564, Isim = "ÖMERLİ", SehirID = 47 });
            ilceler.Add(new Ilce() { ID = 1547, Isim = "NUSAYBİN", SehirID = 47 });
            ilceler.Add(new Ilce() { ID = 1526, Isim = "MİDYAT", SehirID = 47 });
            ilceler.Add(new Ilce() { ID = 1519, Isim = "MAZIDAĞI", SehirID = 47 });
            ilceler.Add(new Ilce() { ID = 1516, Isim = "MERKEZ", SehirID = 47 });
            ilceler.Add(new Ilce() { ID = 1474, Isim = "KIZILTEPE", SehirID = 47 });
            ilceler.Add(new Ilce() { ID = 1273, Isim = "DERİK", SehirID = 47 });
            ilceler.Add(new Ilce() { ID = 99151, Isim = "Milas-Bodrum Havalimanı", SehirID = 48 });
            ilceler.Add(new Ilce() { ID = 99125, Isim = "Dalaman Havalimanı", SehirID = 48 });
            ilceler.Add(new Ilce() { ID = 2090, Isim = "SEYDİKEMER", SehirID = 48 });
            ilceler.Add(new Ilce() { ID = 2089, Isim = "MENTEŞE", SehirID = 48 });
            ilceler.Add(new Ilce() { ID = 1958, Isim = "KAVAKLIDERE", SehirID = 48 });
            ilceler.Add(new Ilce() { ID = 1831, Isim = "ORTACA", SehirID = 48 });
            ilceler.Add(new Ilce() { ID = 1742, Isim = "DALAMAN", SehirID = 48 });
            ilceler.Add(new Ilce() { ID = 1719, Isim = "YATAĞAN", SehirID = 48 });
            ilceler.Add(new Ilce() { ID = 1695, Isim = "ULA", SehirID = 48 });
            ilceler.Add(new Ilce() { ID = 1532, Isim = "MERKEZ", SehirID = 48 });
            ilceler.Add(new Ilce() { ID = 1528, Isim = "MİLAS", SehirID = 48 });
            ilceler.Add(new Ilce() { ID = 1517, Isim = "MARMARİS", SehirID = 48 });
            ilceler.Add(new Ilce() { ID = 1488, Isim = "KÖYCEĞİZ", SehirID = 48 });
            ilceler.Add(new Ilce() { ID = 1331, Isim = "FETHİYE", SehirID = 48 });
            ilceler.Add(new Ilce() { ID = 1266, Isim = "DATÇA", SehirID = 48 });
            ilceler.Add(new Ilce() { ID = 1197, Isim = "BODRUM", SehirID = 48 });
            ilceler.Add(new Ilce() { ID = 99129, Isim = "Muş Havalimanı", SehirID = 49 });
            ilceler.Add(new Ilce() { ID = 1964, Isim = "KORKUT", SehirID = 49 });
            ilceler.Add(new Ilce() { ID = 1801, Isim = "HASKÖY", SehirID = 49 });
            ilceler.Add(new Ilce() { ID = 1711, Isim = "VARTO", SehirID = 49 });
            ilceler.Add(new Ilce() { ID = 1534, Isim = "MERKEZ", SehirID = 49 });
            ilceler.Add(new Ilce() { ID = 1510, Isim = "MALAZGİRT", SehirID = 49 });
            ilceler.Add(new Ilce() { ID = 1213, Isim = "BULANIK", SehirID = 49 });
            ilceler.Add(new Ilce() { ID = 99105, Isim = "Nevşehir Kapadokya Havalimanı", SehirID = 50 });
            ilceler.Add(new Ilce() { ID = 1749, Isim = "ACIGÖL", SehirID = 50 });
            ilceler.Add(new Ilce() { ID = 1707, Isim = "ÜRGÜP", SehirID = 50 });
            ilceler.Add(new Ilce() { ID = 1543, Isim = "MERKEZ", SehirID = 50 });
            ilceler.Add(new Ilce() { ID = 1485, Isim = "KOZAKLI", SehirID = 50 });
            ilceler.Add(new Ilce() { ID = 1374, Isim = "HACIBEKTAŞ", SehirID = 50 });
            ilceler.Add(new Ilce() { ID = 1367, Isim = "GÜLŞEHİR", SehirID = 50 });
            ilceler.Add(new Ilce() { ID = 1274, Isim = "DERİNKUYU", SehirID = 50 });
            ilceler.Add(new Ilce() { ID = 1155, Isim = "AVANOS", SehirID = 50 });
            ilceler.Add(new Ilce() { ID = 1904, Isim = "ÇİFTLİK", SehirID = 51 });
            ilceler.Add(new Ilce() { ID = 1876, Isim = "ALTUNHİSAR", SehirID = 51 });
            ilceler.Add(new Ilce() { ID = 1700, Isim = "ULUKIŞLA", SehirID = 51 });
            ilceler.Add(new Ilce() { ID = 1544, Isim = "MERKEZ", SehirID = 51 });
            ilceler.Add(new Ilce() { ID = 1225, Isim = "ÇAMARDI", SehirID = 51 });
            ilceler.Add(new Ilce() { ID = 1201, Isim = "BOR", SehirID = 51 });
            ilceler.Add(new Ilce() { ID = 99163, Isim = "Ordu-Giresun Havalimanı", SehirID = 52 });
            ilceler.Add(new Ilce() { ID = 2103, Isim = "ALTINORDU", SehirID = 52 });
            ilceler.Add(new Ilce() { ID = 1951, Isim = "KABATAŞ", SehirID = 52 });
            ilceler.Add(new Ilce() { ID = 1950, Isim = "KABADÜZ", SehirID = 52 });
            ilceler.Add(new Ilce() { ID = 1947, Isim = "İKİZCE", SehirID = 52 });
            ilceler.Add(new Ilce() { ID = 1900, Isim = "ÇAYBAŞI", SehirID = 52 });
            ilceler.Add(new Ilce() { ID = 1897, Isim = "ÇATALPINAR", SehirID = 52 });
            ilceler.Add(new Ilce() { ID = 1891, Isim = "ÇAMAŞ", SehirID = 52 });
            ilceler.Add(new Ilce() { ID = 1797, Isim = "GÜRGENTEPE", SehirID = 52 });
            ilceler.Add(new Ilce() { ID = 1795, Isim = "GÜLYALI", SehirID = 52 });
            ilceler.Add(new Ilce() { ID = 1706, Isim = "ÜNYE", SehirID = 52 });
            ilceler.Add(new Ilce() { ID = 1696, Isim = "ULUBEY", SehirID = 52 });
            ilceler.Add(new Ilce() { ID = 1573, Isim = "PERŞEMBE", SehirID = 52 });
            ilceler.Add(new Ilce() { ID = 1552, Isim = "MERKEZ", SehirID = 52 });
            ilceler.Add(new Ilce() { ID = 1525, Isim = "MESUDİYE", SehirID = 52 });
            ilceler.Add(new Ilce() { ID = 1493, Isim = "KUMRU", SehirID = 52 });
            ilceler.Add(new Ilce() { ID = 1482, Isim = "KORGAN", SehirID = 52 });
            ilceler.Add(new Ilce() { ID = 1358, Isim = "GÖLKÖY", SehirID = 52 });
            ilceler.Add(new Ilce() { ID = 1328, Isim = "FATSA", SehirID = 52 });
            ilceler.Add(new Ilce() { ID = 1158, Isim = "AYBASTI", SehirID = 52 });
            ilceler.Add(new Ilce() { ID = 1119, Isim = "AKKUŞ", SehirID = 52 });
            ilceler.Add(new Ilce() { ID = 1949, Isim = "İYİDERE", SehirID = 53 });
            ilceler.Add(new Ilce() { ID = 1943, Isim = "HEMŞİN", SehirID = 53 });
            ilceler.Add(new Ilce() { ID = 1908, Isim = "DEREPAZARI", SehirID = 53 });
            ilceler.Add(new Ilce() { ID = 1796, Isim = "GÜNEYSU", SehirID = 53 });
            ilceler.Add(new Ilce() { ID = 1586, Isim = "MERKEZ", SehirID = 53 });
            ilceler.Add(new Ilce() { ID = 1569, Isim = "PAZAR", SehirID = 53 });
            ilceler.Add(new Ilce() { ID = 1428, Isim = "KALKANDERE", SehirID = 53 });
            ilceler.Add(new Ilce() { ID = 1405, Isim = "İKİZDERE", SehirID = 53 });
            ilceler.Add(new Ilce() { ID = 1332, Isim = "FINDIKLI", SehirID = 53 });
            ilceler.Add(new Ilce() { ID = 1241, Isim = "ÇAYELİ", SehirID = 53 });
            ilceler.Add(new Ilce() { ID = 1228, Isim = "ÇAMLIHEMŞİN", SehirID = 53 });
            ilceler.Add(new Ilce() { ID = 1146, Isim = "ARDEŞEN", SehirID = 53 });
            ilceler.Add(new Ilce() { ID = 2071, Isim = "SERDİVAN", SehirID = 54 });
            ilceler.Add(new Ilce() { ID = 2070, Isim = "ERENLER", SehirID = 54 });
            ilceler.Add(new Ilce() { ID = 2069, Isim = "ARİFİYE", SehirID = 54 });
            ilceler.Add(new Ilce() { ID = 2068, Isim = "ADAPAZARI", SehirID = 54 });
            ilceler.Add(new Ilce() { ID = 1986, Isim = "SÖĞÜTLÜ", SehirID = 54 });
            ilceler.Add(new Ilce() { ID = 1955, Isim = "KARAPÜRÇEK", SehirID = 54 });
            ilceler.Add(new Ilce() { ID = 1925, Isim = "FERİZLİ", SehirID = 54 });
            ilceler.Add(new Ilce() { ID = 1847, Isim = "TARAKLI", SehirID = 54 });
            ilceler.Add(new Ilce() { ID = 1833, Isim = "PAMUKOVA", SehirID = 54 });
            ilceler.Add(new Ilce() { ID = 1818, Isim = "KOCAALİ", SehirID = 54 });
            ilceler.Add(new Ilce() { ID = 1595, Isim = "SAPANCA", SehirID = 54 });
            ilceler.Add(new Ilce() { ID = 1589, Isim = "MERKEZ", SehirID = 54 });
            ilceler.Add(new Ilce() { ID = 1453, Isim = "KAYNARCA", SehirID = 54 });
            ilceler.Add(new Ilce() { ID = 1442, Isim = "KARASU", SehirID = 54 });
            ilceler.Add(new Ilce() { ID = 1391, Isim = "HENDEK", SehirID = 54 });
            ilceler.Add(new Ilce() { ID = 1351, Isim = "GEYVE", SehirID = 54 });
            ilceler.Add(new Ilce() { ID = 1123, Isim = "AKYAZI", SehirID = 54 });
            ilceler.Add(new Ilce() { ID = 99127, Isim = "Samsun Çarşamba Havalimanı", SehirID = 55 });
            ilceler.Add(new Ilce() { ID = 2074, Isim = "İLKADIM", SehirID = 55 });
            ilceler.Add(new Ilce() { ID = 2073, Isim = "CANİK", SehirID = 55 });
            ilceler.Add(new Ilce() { ID = 2072, Isim = "ATAKUM", SehirID = 55 });
            ilceler.Add(new Ilce() { ID = 1993, Isim = "YAKAKENT", SehirID = 55 });
            ilceler.Add(new Ilce() { ID = 1879, Isim = "AYVACIK", SehirID = 55 });
            ilceler.Add(new Ilce() { ID = 1849, Isim = "TEKKEKÖY", SehirID = 55 });
            ilceler.Add(new Ilce() { ID = 1838, Isim = "SALIPAZARI", SehirID = 55 });
            ilceler.Add(new Ilce() { ID = 1830, Isim = "19 MAYIS", SehirID = 55 });
            ilceler.Add(new Ilce() { ID = 1763, Isim = "ASARCIK", SehirID = 55 });
            ilceler.Add(new Ilce() { ID = 1712, Isim = "VEZİRKÖPRÜ", SehirID = 55 });
            ilceler.Add(new Ilce() { ID = 1676, Isim = "TERME", SehirID = 55 });
            ilceler.Add(new Ilce() { ID = 1593, Isim = "MERKEZ", SehirID = 55 });
            ilceler.Add(new Ilce() { ID = 1501, Isim = "LADİK", SehirID = 55 });
            ilceler.Add(new Ilce() { ID = 1452, Isim = "KAVAK", SehirID = 55 });
            ilceler.Add(new Ilce() { ID = 1386, Isim = "HAVZA", SehirID = 55 });
            ilceler.Add(new Ilce() { ID = 1234, Isim = "ÇARŞAMBA", SehirID = 55 });
            ilceler.Add(new Ilce() { ID = 1164, Isim = "BAFRA", SehirID = 55 });
            ilceler.Add(new Ilce() { ID = 1125, Isim = "ALAÇAM", SehirID = 55 });
            ilceler.Add(new Ilce() { ID = 99115, Isim = "Siirt Havalimanı", SehirID = 56 });
            ilceler.Add(new Ilce() { ID = 1878, Isim = "TİLLO", SehirID = 56 });
            ilceler.Add(new Ilce() { ID = 1662, Isim = "ŞİRVAN", SehirID = 56 });
            ilceler.Add(new Ilce() { ID = 1620, Isim = "MERKEZ", SehirID = 56 });
            ilceler.Add(new Ilce() { ID = 1575, Isim = "PERVARİ", SehirID = 56 });
            ilceler.Add(new Ilce() { ID = 1495, Isim = "KURTALAN", SehirID = 56 });
            ilceler.Add(new Ilce() { ID = 1317, Isim = "ERUH", SehirID = 56 });
            ilceler.Add(new Ilce() { ID = 1179, Isim = "BAYKAN", SehirID = 56 });
            ilceler.Add(new Ilce() { ID = 99116, Isim = "Sinop Havalimanı", SehirID = 57 });
            ilceler.Add(new Ilce() { ID = 1981, Isim = "SARAYDÜZÜ", SehirID = 57 });
            ilceler.Add(new Ilce() { ID = 1910, Isim = "DİKMEN", SehirID = 57 });
            ilceler.Add(new Ilce() { ID = 1693, Isim = "TÜRKELİ", SehirID = 57 });
            ilceler.Add(new Ilce() { ID = 1627, Isim = "MERKEZ", SehirID = 57 });
            ilceler.Add(new Ilce() { ID = 1349, Isim = "GERZE", SehirID = 57 });
            ilceler.Add(new Ilce() { ID = 1314, Isim = "ERFELEK", SehirID = 57 });
            ilceler.Add(new Ilce() { ID = 1290, Isim = "DURAĞAN", SehirID = 57 });
            ilceler.Add(new Ilce() { ID = 1204, Isim = "BOYABAT", SehirID = 57 });
            ilceler.Add(new Ilce() { ID = 1156, Isim = "AYANCIK", SehirID = 57 });
            ilceler.Add(new Ilce() { ID = 99117, Isim = "Sivas Nuri Demirağ Havalimanı", SehirID = 58 });
            ilceler.Add(new Ilce() { ID = 1991, Isim = "ULAŞ", SehirID = 58 });
            ilceler.Add(new Ilce() { ID = 1927, Isim = "GÖLOVA", SehirID = 58 });
            ilceler.Add(new Ilce() { ID = 1913, Isim = "DOĞANŞAR", SehirID = 58 });
            ilceler.Add(new Ilce() { ID = 1875, Isim = "ALTINYAYLA", SehirID = 58 });
            ilceler.Add(new Ilce() { ID = 1870, Isim = "AKINCILAR", SehirID = 58 });
            ilceler.Add(new Ilce() { ID = 1738, Isim = "ZARA", SehirID = 58 });
            ilceler.Add(new Ilce() { ID = 1731, Isim = "YILDIZELİ", SehirID = 58 });
            ilceler.Add(new Ilce() { ID = 1650, Isim = "ŞARKIŞLA", SehirID = 58 });
            ilceler.Add(new Ilce() { ID = 1646, Isim = "SUŞEHRİ", SehirID = 58 });
            ilceler.Add(new Ilce() { ID = 1628, Isim = "MERKEZ", SehirID = 58 });
            ilceler.Add(new Ilce() { ID = 1484, Isim = "KOYULHİSAR", SehirID = 58 });
            ilceler.Add(new Ilce() { ID = 1431, Isim = "KANGAL", SehirID = 58 });
            ilceler.Add(new Ilce() { ID = 1407, Isim = "İMRANLI", SehirID = 58 });
            ilceler.Add(new Ilce() { ID = 1376, Isim = "HAFİK", SehirID = 58 });
            ilceler.Add(new Ilce() { ID = 1373, Isim = "GÜRÜN", SehirID = 58 });
            ilceler.Add(new Ilce() { ID = 1342, Isim = "GEMEREK", SehirID = 58 });
            ilceler.Add(new Ilce() { ID = 1282, Isim = "DİVRİĞİ", SehirID = 58 });
            ilceler.Add(new Ilce() { ID = 99119, Isim = "Tekirdağ Çorlu Havalimanı", SehirID = 59 });
            ilceler.Add(new Ilce() { ID = 2096, Isim = "SÜLEYMANPAŞA", SehirID = 59 });
            ilceler.Add(new Ilce() { ID = 2095, Isim = "KAPAKLI", SehirID = 59 });
            ilceler.Add(new Ilce() { ID = 2094, Isim = "ERGENE", SehirID = 59 });
            ilceler.Add(new Ilce() { ID = 1825, Isim = "MARMARAEREĞLİSİ", SehirID = 59 });
            ilceler.Add(new Ilce() { ID = 1673, Isim = "MERKEZ", SehirID = 59 });
            ilceler.Add(new Ilce() { ID = 1652, Isim = "ŞARKÖY", SehirID = 59 });
            ilceler.Add(new Ilce() { ID = 1596, Isim = "SARAY", SehirID = 59 });
            ilceler.Add(new Ilce() { ID = 1538, Isim = "MURATLI", SehirID = 59 });
            ilceler.Add(new Ilce() { ID = 1511, Isim = "MALKARA", SehirID = 59 });
            ilceler.Add(new Ilce() { ID = 1388, Isim = "HAYRABOLU", SehirID = 59 });
            ilceler.Add(new Ilce() { ID = 1258, Isim = "ÇORLU", SehirID = 59 });
            ilceler.Add(new Ilce() { ID = 1250, Isim = "ÇERKEZKÖY", SehirID = 59 });
            ilceler.Add(new Ilce() { ID = 99169, Isim = "Tokat Havalimanı", SehirID = 60 });
            ilceler.Add(new Ilce() { ID = 1987, Isim = "SULUSARAY", SehirID = 60 });
            ilceler.Add(new Ilce() { ID = 1883, Isim = "BAŞÇİFTLİK", SehirID = 60 });
            ilceler.Add(new Ilce() { ID = 1858, Isim = "YEŞİLYURT", SehirID = 60 });
            ilceler.Add(new Ilce() { ID = 1834, Isim = "PAZAR", SehirID = 60 });
            ilceler.Add(new Ilce() { ID = 1740, Isim = "ZİLE", SehirID = 60 });
            ilceler.Add(new Ilce() { ID = 1690, Isim = "TURHAL", SehirID = 60 });
            ilceler.Add(new Ilce() { ID = 1679, Isim = "MERKEZ", SehirID = 60 });
            ilceler.Add(new Ilce() { ID = 1584, Isim = "REŞADİYE", SehirID = 60 });
            ilceler.Add(new Ilce() { ID = 1545, Isim = "NİKSAR", SehirID = 60 });
            ilceler.Add(new Ilce() { ID = 1308, Isim = "ERBAA", SehirID = 60 });
            ilceler.Add(new Ilce() { ID = 1151, Isim = "ARTOVA", SehirID = 60 });
            ilceler.Add(new Ilce() { ID = 1129, Isim = "ALMUS", SehirID = 60 });
            ilceler.Add(new Ilce() { ID = 99152, Isim = "Trabzon Havalimanı", SehirID = 61 });
            ilceler.Add(new Ilce() { ID = 2097, Isim = "ORTAHİSAR", SehirID = 61 });
            ilceler.Add(new Ilce() { ID = 1966, Isim = "KÖPRÜBAŞI", SehirID = 61 });
            ilceler.Add(new Ilce() { ID = 1942, Isim = "HAYRAT", SehirID = 61 });
            ilceler.Add(new Ilce() { ID = 1917, Isim = "DÜZKÖY", SehirID = 61 });
            ilceler.Add(new Ilce() { ID = 1909, Isim = "DERNEKPAZARI", SehirID = 61 });
            ilceler.Add(new Ilce() { ID = 1896, Isim = "ÇARŞIBAŞI", SehirID = 61 });
            ilceler.Add(new Ilce() { ID = 1842, Isim = "ŞALPAZARI", SehirID = 61 });
            ilceler.Add(new Ilce() { ID = 1775, Isim = "BEŞİKDÜZÜ", SehirID = 61 });
            ilceler.Add(new Ilce() { ID = 1732, Isim = "YOMRA", SehirID = 61 });
            ilceler.Add(new Ilce() { ID = 1709, Isim = "VAKFIKEBİR", SehirID = 61 });
            ilceler.Add(new Ilce() { ID = 1686, Isim = "MERKEZ", SehirID = 61 });
            ilceler.Add(new Ilce() { ID = 1681, Isim = "TONYA", SehirID = 61 });
            ilceler.Add(new Ilce() { ID = 1647, Isim = "SÜRMENE", SehirID = 61 });
            ilceler.Add(new Ilce() { ID = 1548, Isim = "OF", SehirID = 61 });
            ilceler.Add(new Ilce() { ID = 1507, Isim = "MAÇKA", SehirID = 61 });
            ilceler.Add(new Ilce() { ID = 1244, Isim = "ÇAYKARA", SehirID = 61 });
            ilceler.Add(new Ilce() { ID = 1150, Isim = "ARSİN", SehirID = 61 });
            ilceler.Add(new Ilce() { ID = 1141, Isim = "ARAKLI", SehirID = 61 });
            ilceler.Add(new Ilce() { ID = 1113, Isim = "AKÇAABAT", SehirID = 61 });
            ilceler.Add(new Ilce() { ID = 1688, Isim = "MERKEZ", SehirID = 62 });
            ilceler.Add(new Ilce() { ID = 1581, Isim = "PÜLÜMÜR", SehirID = 62 });
            ilceler.Add(new Ilce() { ID = 1574, Isim = "PERTEK", SehirID = 62 });
            ilceler.Add(new Ilce() { ID = 1562, Isim = "OVACIK", SehirID = 62 });
            ilceler.Add(new Ilce() { ID = 1541, Isim = "NAZIMİYE", SehirID = 62 });
            ilceler.Add(new Ilce() { ID = 1518, Isim = "MAZGİRT", SehirID = 62 });
            ilceler.Add(new Ilce() { ID = 1397, Isim = "HOZAT", SehirID = 62 });
            ilceler.Add(new Ilce() { ID = 1247, Isim = "ÇEMİŞGEZEK", SehirID = 62 });
            ilceler.Add(new Ilce() { ID = 99138, Isim = "Şanlıurfa GAP Havalimanı", SehirID = 63 });
            ilceler.Add(new Ilce() { ID = 2093, Isim = "KARAKÖPRÜ", SehirID = 63 });
            ilceler.Add(new Ilce() { ID = 2092, Isim = "HALİLİYE", SehirID = 63 });
            ilceler.Add(new Ilce() { ID = 2091, Isim = "EYYÜBİYE", SehirID = 63 });
            ilceler.Add(new Ilce() { ID = 1800, Isim = "HARRAN", SehirID = 63 });
            ilceler.Add(new Ilce() { ID = 1713, Isim = "VİRANŞEHİR", SehirID = 63 });
            ilceler.Add(new Ilce() { ID = 1702, Isim = "MERKEZ", SehirID = 63 });
            ilceler.Add(new Ilce() { ID = 1643, Isim = "SURUÇ", SehirID = 63 });
            ilceler.Add(new Ilce() { ID = 1630, Isim = "SİVEREK", SehirID = 63 });
            ilceler.Add(new Ilce() { ID = 1393, Isim = "HİLVAN", SehirID = 63 });
            ilceler.Add(new Ilce() { ID = 1378, Isim = "HALFETİ", SehirID = 63 });
            ilceler.Add(new Ilce() { ID = 1220, Isim = "CEYLANPINAR", SehirID = 63 });
            ilceler.Add(new Ilce() { ID = 1209, Isim = "BOZOVA", SehirID = 63 });
            ilceler.Add(new Ilce() { ID = 1194, Isim = "BİRECİK", SehirID = 63 });
            ilceler.Add(new Ilce() { ID = 1115, Isim = "AKÇAKALE", SehirID = 63 });
            ilceler.Add(new Ilce() { ID = 99120, Isim = "Uşak Havalimanı", SehirID = 64 });
            ilceler.Add(new Ilce() { ID = 1704, Isim = "MERKEZ", SehirID = 64 });
            ilceler.Add(new Ilce() { ID = 1697, Isim = "ULUBEY", SehirID = 64 });
            ilceler.Add(new Ilce() { ID = 1629, Isim = "SİVASLI", SehirID = 64 });
            ilceler.Add(new Ilce() { ID = 1436, Isim = "KARAHALLI", SehirID = 64 });
            ilceler.Add(new Ilce() { ID = 1323, Isim = "EŞME", SehirID = 64 });
            ilceler.Add(new Ilce() { ID = 1170, Isim = "BANAZ", SehirID = 64 });
            ilceler.Add(new Ilce() { ID = 99146, Isim = "Ferit Melen Havalimanı", SehirID = 65 });
            ilceler.Add(new Ilce() { ID = 2099, Isim = "TUŞBA", SehirID = 65 });
            ilceler.Add(new Ilce() { ID = 2098, Isim = "İPEKYOLU", SehirID = 65 });
            ilceler.Add(new Ilce() { ID = 1980, Isim = "SARAY", SehirID = 65 });
            ilceler.Add(new Ilce() { ID = 1918, Isim = "EDREMİT", SehirID = 65 });
            ilceler.Add(new Ilce() { ID = 1786, Isim = "ÇALDIRAN", SehirID = 65 });
            ilceler.Add(new Ilce() { ID = 1770, Isim = "BAHÇESARAY", SehirID = 65 });
            ilceler.Add(new Ilce() { ID = 1710, Isim = "MERKEZ", SehirID = 65 });
            ilceler.Add(new Ilce() { ID = 1565, Isim = "ÖZALP", SehirID = 65 });
            ilceler.Add(new Ilce() { ID = 1533, Isim = "MURADİYE", SehirID = 65 });
            ilceler.Add(new Ilce() { ID = 1372, Isim = "GÜRPINAR", SehirID = 65 });
            ilceler.Add(new Ilce() { ID = 1350, Isim = "GEVAŞ", SehirID = 65 });
            ilceler.Add(new Ilce() { ID = 1309, Isim = "ERCİŞ", SehirID = 65 });
            ilceler.Add(new Ilce() { ID = 1236, Isim = "ÇATAK", SehirID = 65 });
            ilceler.Add(new Ilce() { ID = 1175, Isim = "BAŞKALE", SehirID = 65 });
            ilceler.Add(new Ilce() { ID = 1998, Isim = "YENİFAKILI", SehirID = 66 });
            ilceler.Add(new Ilce() { ID = 1982, Isim = "SARAYKENT", SehirID = 66 });
            ilceler.Add(new Ilce() { ID = 1952, Isim = "KADIŞEHRİ", SehirID = 66 });
            ilceler.Add(new Ilce() { ID = 1895, Isim = "ÇANDIR", SehirID = 66 });
            ilceler.Add(new Ilce() { ID = 1877, Isim = "AYDINCIK", SehirID = 66 });
            ilceler.Add(new Ilce() { ID = 1733, Isim = "MERKEZ", SehirID = 66 });
            ilceler.Add(new Ilce() { ID = 1726, Isim = "YERKÖY", SehirID = 66 });
            ilceler.Add(new Ilce() { ID = 1655, Isim = "ŞEFAATLİ", SehirID = 66 });
            ilceler.Add(new Ilce() { ID = 1635, Isim = "SORGUN", SehirID = 66 });
            ilceler.Add(new Ilce() { ID = 1602, Isim = "SARIKAYA", SehirID = 66 });
            ilceler.Add(new Ilce() { ID = 1245, Isim = "ÇEKEREK", SehirID = 66 });
            ilceler.Add(new Ilce() { ID = 1242, Isim = "ÇAYIRALAN", SehirID = 66 });
            ilceler.Add(new Ilce() { ID = 1198, Isim = "BOĞAZLIYAN", SehirID = 66 });
            ilceler.Add(new Ilce() { ID = 1117, Isim = "AKDAĞMADENİ", SehirID = 66 });
            ilceler.Add(new Ilce() { ID = 99147, Isim = "Zonguldak Havalimanı", SehirID = 67 });
            ilceler.Add(new Ilce() { ID = 2101, Isim = "KOZLU", SehirID = 67 });
            ilceler.Add(new Ilce() { ID = 2100, Isim = "KİLİMLİ", SehirID = 67 });
            ilceler.Add(new Ilce() { ID = 1926, Isim = "GÖKÇEBEY", SehirID = 67 });
            ilceler.Add(new Ilce() { ID = 1758, Isim = "ALAPLI", SehirID = 67 });
            ilceler.Add(new Ilce() { ID = 1741, Isim = "MERKEZ", SehirID = 67 });
            ilceler.Add(new Ilce() { ID = 1313, Isim = "EREĞLİ", SehirID = 67 });
            ilceler.Add(new Ilce() { ID = 1276, Isim = "DEVREK", SehirID = 67 });
            ilceler.Add(new Ilce() { ID = 1240, Isim = "ÇAYCUMA", SehirID = 67 });
            ilceler.Add(new Ilce() { ID = 2106, Isim = "SULTANHANI", SehirID = 68 });
            ilceler.Add(new Ilce() { ID = 1932, Isim = "GÜLAĞAÇ", SehirID = 68 });
            ilceler.Add(new Ilce() { ID = 1921, Isim = "ESKİL", SehirID = 68 });
            ilceler.Add(new Ilce() { ID = 1866, Isim = "SARIYAHŞİ", SehirID = 68 });
            ilceler.Add(new Ilce() { ID = 1861, Isim = "GÜZELYURT", SehirID = 68 });
            ilceler.Add(new Ilce() { ID = 1860, Isim = "AĞAÇÖREN", SehirID = 68 });
            ilceler.Add(new Ilce() { ID = 1557, Isim = "ORTAKÖY", SehirID = 68 });
            ilceler.Add(new Ilce() { ID = 1120, Isim = "MERKEZ", SehirID = 68 });
            ilceler.Add(new Ilce() { ID = 1788, Isim = "DEMİRÖZÜ", SehirID = 69 });
            ilceler.Add(new Ilce() { ID = 1767, Isim = "AYDINTEPE", SehirID = 69 });
            ilceler.Add(new Ilce() { ID = 1176, Isim = "MERKEZ", SehirID = 69 });
            ilceler.Add(new Ilce() { ID = 1983, Isim = "SARIVELİLER", SehirID = 70 });
            ilceler.Add(new Ilce() { ID = 1884, Isim = "BAŞYAYLA", SehirID = 70 });
            ilceler.Add(new Ilce() { ID = 1862, Isim = "KAZIMKARABEKİR", SehirID = 70 });
            ilceler.Add(new Ilce() { ID = 1768, Isim = "AYRANCI", SehirID = 70 });
            ilceler.Add(new Ilce() { ID = 1439, Isim = "MERKEZ", SehirID = 70 });
            ilceler.Add(new Ilce() { ID = 1316, Isim = "ERMENEK", SehirID = 70 });
            ilceler.Add(new Ilce() { ID = 1992, Isim = "YAHŞİHAN", SehirID = 71 });
            ilceler.Add(new Ilce() { ID = 1954, Isim = "KARAKEÇİLİ", SehirID = 71 });
            ilceler.Add(new Ilce() { ID = 1901, Isim = "ÇELEBİ", SehirID = 71 });
            ilceler.Add(new Ilce() { ID = 1882, Isim = "BALIŞEYH", SehirID = 71 });
            ilceler.Add(new Ilce() { ID = 1880, Isim = "BAHŞİLİ", SehirID = 71 });
            ilceler.Add(new Ilce() { ID = 1638, Isim = "SULAKYURT", SehirID = 71 });
            ilceler.Add(new Ilce() { ID = 1469, Isim = "MERKEZ", SehirID = 71 });
            ilceler.Add(new Ilce() { ID = 1463, Isim = "KESKİN", SehirID = 71 });
            ilceler.Add(new Ilce() { ID = 1268, Isim = "DELİCE", SehirID = 71 });
            ilceler.Add(new Ilce() { ID = 99108, Isim = "Batman Havalimanı", SehirID = 72 });
            ilceler.Add(new Ilce() { ID = 1941, Isim = "HASANKEYF", SehirID = 72 });
            ilceler.Add(new Ilce() { ID = 1607, Isim = "SASON", SehirID = 72 });
            ilceler.Add(new Ilce() { ID = 1487, Isim = "KOZLUK", SehirID = 72 });
            ilceler.Add(new Ilce() { ID = 1345, Isim = "GERCÜŞ", SehirID = 72 });
            ilceler.Add(new Ilce() { ID = 1184, Isim = "BEŞİRİ", SehirID = 72 });
            ilceler.Add(new Ilce() { ID = 1174, Isim = "MERKEZ", SehirID = 72 });
            ilceler.Add(new Ilce() { ID = 99118, Isim = "Şırnak Şerafettin Elçi Havalimanı", SehirID = 73 });
            ilceler.Add(new Ilce() { ID = 1931, Isim = "GÜÇLÜKONAK", SehirID = 73 });
            ilceler.Add(new Ilce() { ID = 1698, Isim = "ULUDERE", SehirID = 73 });
            ilceler.Add(new Ilce() { ID = 1661, Isim = "MERKEZ", SehirID = 73 });
            ilceler.Add(new Ilce() { ID = 1623, Isim = "SİLOPİ", SehirID = 73 });
            ilceler.Add(new Ilce() { ID = 1403, Isim = "İDİL", SehirID = 73 });
            ilceler.Add(new Ilce() { ID = 1223, Isim = "CİZRE", SehirID = 73 });
            ilceler.Add(new Ilce() { ID = 1189, Isim = "BEYTÜŞŞEBAP", SehirID = 73 });
            ilceler.Add(new Ilce() { ID = 1761, Isim = "AMASRA", SehirID = 74 });
            ilceler.Add(new Ilce() { ID = 1701, Isim = "ULUS", SehirID = 74 });
            ilceler.Add(new Ilce() { ID = 1496, Isim = "KURUCAŞİLE", SehirID = 74 });
            ilceler.Add(new Ilce() { ID = 1172, Isim = "MERKEZ", SehirID = 74 });
            ilceler.Add(new Ilce() { ID = 2008, Isim = "DAMAL", SehirID = 75 });
            ilceler.Add(new Ilce() { ID = 1579, Isim = "POSOF", SehirID = 75 });
            ilceler.Add(new Ilce() { ID = 1380, Isim = "HANAK", SehirID = 75 });
            ilceler.Add(new Ilce() { ID = 1356, Isim = "GÖLE", SehirID = 75 });
            ilceler.Add(new Ilce() { ID = 1252, Isim = "ÇILDIR", SehirID = 75 });
            ilceler.Add(new Ilce() { ID = 1144, Isim = "MERKEZ", SehirID = 75 });
            ilceler.Add(new Ilce() { ID = 99111, Isim = "Iğdır Havalimanı", SehirID = 76 });
            ilceler.Add(new Ilce() { ID = 2011, Isim = "KARAKOYUNLU", SehirID = 76 });
            ilceler.Add(new Ilce() { ID = 1692, Isim = "TUZLUCA", SehirID = 76 });
            ilceler.Add(new Ilce() { ID = 1398, Isim = "MERKEZ", SehirID = 76 });
            ilceler.Add(new Ilce() { ID = 1142, Isim = "ARALIK", SehirID = 76 });
            ilceler.Add(new Ilce() { ID = 2026, Isim = "TERMAL", SehirID = 77 });
            ilceler.Add(new Ilce() { ID = 2022, Isim = "ÇİFTLİKKÖY", SehirID = 77 });
            ilceler.Add(new Ilce() { ID = 2021, Isim = "ÇINARCIK", SehirID = 77 });
            ilceler.Add(new Ilce() { ID = 2020, Isim = "ARMUTLU", SehirID = 77 });
            ilceler.Add(new Ilce() { ID = 2019, Isim = "ALTINOVA", SehirID = 77 });
            ilceler.Add(new Ilce() { ID = 1716, Isim = "MERKEZ", SehirID = 77 });
            ilceler.Add(new Ilce() { ID = 1856, Isim = "YENİCE", SehirID = 78 });
            ilceler.Add(new Ilce() { ID = 1587, Isim = "SAFRANBOLU", SehirID = 78 });
            ilceler.Add(new Ilce() { ID = 1561, Isim = "OVACIK", SehirID = 78 });
            ilceler.Add(new Ilce() { ID = 1433, Isim = "MERKEZ", SehirID = 78 });
            ilceler.Add(new Ilce() { ID = 1321, Isim = "ESKİPAZAR", SehirID = 78 });
            ilceler.Add(new Ilce() { ID = 1296, Isim = "EFLANİ", SehirID = 78 });
            ilceler.Add(new Ilce() { ID = 2025, Isim = "POLATELİ", SehirID = 79 });
            ilceler.Add(new Ilce() { ID = 2024, Isim = "MUSABEYLİ", SehirID = 79 });
            ilceler.Add(new Ilce() { ID = 2023, Isim = "ELBEYLİ", SehirID = 79 });
            ilceler.Add(new Ilce() { ID = 1476, Isim = "MERKEZ", SehirID = 79 });
            ilceler.Add(new Ilce() { ID = 2029, Isim = "TOPRAKKALE", SehirID = 80 });
            ilceler.Add(new Ilce() { ID = 2028, Isim = "SUMBAS", SehirID = 80 });
            ilceler.Add(new Ilce() { ID = 2027, Isim = "HASANBEYLİ", SehirID = 80 });
            ilceler.Add(new Ilce() { ID = 1743, Isim = "DÜZİÇİ", SehirID = 80 });
            ilceler.Add(new Ilce() { ID = 1560, Isim = "MERKEZ", SehirID = 80 });
            ilceler.Add(new Ilce() { ID = 1423, Isim = "KADİRLİ", SehirID = 80 });
            ilceler.Add(new Ilce() { ID = 1165, Isim = "BAHÇE", SehirID = 80 });
            ilceler.Add(new Ilce() { ID = 2031, Isim = "KAYNAŞLI", SehirID = 81 });
            ilceler.Add(new Ilce() { ID = 2017, Isim = "GÜMÜŞOVA", SehirID = 81 });
            ilceler.Add(new Ilce() { ID = 1905, Isim = "ÇİLİMLİ", SehirID = 81 });
            ilceler.Add(new Ilce() { ID = 1794, Isim = "GÖLYAKA", SehirID = 81 });
            ilceler.Add(new Ilce() { ID = 1784, Isim = "CUMAYERİ", SehirID = 81 });
            ilceler.Add(new Ilce() { ID = 1730, Isim = "YIĞILCA", SehirID = 81 });
            ilceler.Add(new Ilce() { ID = 1292, Isim = "MERKEZ", SehirID = 81 });
            ilceler.Add(new Ilce() { ID = 1116, Isim = "AKÇAKOCA", SehirID = 81 });
            return ilceler;
        }

        public List<Ilce> SeciliIlceDoldur(int sID)
        {
            List<Ilce> ilceler = IlceDoldur();
            foreach (Ilce item in ilceler)
            {
                if (item.SehirID == sID)
                {
                    ilceler.Add(item);
                }
            }
            return ilceler;
        }

        private void btn_getir_Click(object sender, EventArgs e)
        {

        }
    }
}
